export interface WordPair {
  civilian: string;
  undercover: string;
}

export interface WordPack {
  id: string;
  name: string;
  emoji: string;
  description: string;
  pairs: WordPair[];
}

export const WORD_PACKS: WordPack[] = [
  // ─────────────────────────────────────────────
  // BOLLYWOOD
  // ─────────────────────────────────────────────
  {
    id: "bollywood",
    name: "Bollywood",
    emoji: "🎬",
    description: "Hindi cinema 2000–2025",
    pairs: [
      { civilian: "Lagaan", undercover: "Swades" },
      { civilian: "Dilwale", undercover: "Mohabbatein" },
      { civilian: "Kabhi Khushi Kabhie Gham", undercover: "Kabhi Alvida Naa Kehna" },
      { civilian: "Devdas", undercover: "Umrao Jaan" },
      { civilian: "Dhoom", undercover: "Don" },
      { civilian: "Rang De Basanti", undercover: "Lakshya" },
      { civilian: "Munna Bhai MBBS", undercover: "Lage Raho Munna Bhai" },
      { civilian: "3 Idiots", undercover: "Chhichhore" },
      { civilian: "Taare Zameen Par", undercover: "Stanley Ka Dabba" },
      { civilian: "Jab We Met", undercover: "Love Aaj Kal" },
      { civilian: "Chak De India", undercover: "Bhaag Milkha Bhaag" },
      { civilian: "Dabangg", undercover: "Singham" },
      { civilian: "Zindagi Na Milegi Dobara", undercover: "Dil Dhadakne Do" },
      { civilian: "Barfi", undercover: "Rockstar" },
      { civilian: "Gangs of Wasseypur", undercover: "Ugly" },
      { civilian: "Queen", undercover: "Highway" },
      { civilian: "Bajrangi Bhaijaan", undercover: "Sultan" },
      { civilian: "Dangal", undercover: "Secret Superstar" },
      { civilian: "Raazi", undercover: "Uri" },
      { civilian: "Gully Boy", undercover: "Udta Punjab" },
      { civilian: "Andhadhun", undercover: "Badla" },
      { civilian: "Article 15", undercover: "Thappad" },
      { civilian: "Shershaah", undercover: "Sam Bahadur" },
      { civilian: "Pathaan", undercover: "War" },
      { civilian: "Brahmastra", undercover: "Kalki 2898 AD" },
      { civilian: "Animal", undercover: "Kabir Singh" },
      { civilian: "Rocky Aur Rani", undercover: "Ae Dil Hai Mushkil" },
      { civilian: "Jawan", undercover: "Bade Miyan Chote Miyan" },
      { civilian: "Laal Singh Chaddha", undercover: "Atrangi Re" },
      { civilian: "12th Fail", undercover: "Super 30" },
      { civilian: "Kal Ho Naa Ho", undercover: "Dil To Pagal Hai" },
      { civilian: "Hera Pheri", undercover: "Welcome" },
      { civilian: "Golmaal", undercover: "Bhool Bhulaiya" },
      { civilian: "Padmaavat", undercover: "Bajirao Mastani" },
      { civilian: "PK", undercover: "OMG" },
      { civilian: "Dil Chahta Hai", undercover: "Lakshya" },
      { civilian: "Veer-Zaara", undercover: "Fanaa" },
      { civilian: "Black", undercover: "Saawariya" },
      { civilian: "Koi Mil Gaya", undercover: "Krish" },
      { civilian: "Mission Kashmir", undercover: "Haider" },
      { civilian: "Talaash", undercover: "Kahaani" },
      { civilian: "Stree", undercover: "Bhediya" },
      { civilian: "Tumbbad", undercover: "Raat Akeli Hai" },
      { civilian: "Lootera", undercover: "Sonchiriya" },
      { civilian: "Masaan", undercover: "Newton" },
      { civilian: "Trapped", undercover: "Shahid" },
      { civilian: "Aligarh", undercover: "Omerta" },
      { civilian: "Drishyam", undercover: "Andhadhun" },
      { civilian: "Toilet Ek Prem Katha", undercover: "Pad Man" },
      { civilian: "Bala", undercover: "Ujda Chaman" },
      { civilian: "Ludo", undercover: "Ghost Stories" },
      { civilian: "Haseen Dillruba", undercover: "Darlings" },
      { civilian: "Tu Jhoothi Main Makkaar", undercover: "Love Ranjan" },
      { civilian: "Jogi", undercover: "Sardar Udham" },
      { civilian: "Bheed", undercover: "Panga" },
      { civilian: "Crew", undercover: "Merry Christmas" },
      { civilian: "Stree 2", undercover: "Munjya" },
      { civilian: "Fukrey", undercover: "Delhi Belly" },
      { civilian: "Go Goa Gone", undercover: "Happy Ending" },
      { civilian: "Sonu Ke Titu Ki Sweety", undercover: "De De Pyaar De" },
    ],
  },

  // ─────────────────────────────────────────────
  // TOLLYWOOD
  // ─────────────────────────────────────────────
  {
    id: "tollywood",
    name: "Tollywood",
    emoji: "🎭",
    description: "Telugu & Tamil cinema 2000–2025",
    pairs: [
      { civilian: "Baahubali", undercover: "RRR" },
      { civilian: "Pushpa", undercover: "Arjun Reddy" },
      { civilian: "Magadheera", undercover: "Eega" },
      { civilian: "Pokiri", undercover: "Athadu" },
      { civilian: "Sye Raa", undercover: "Khaidi No 150" },
      { civilian: "Jersey", undercover: "Maharshi" },
      { civilian: "Ala Vaikunthapurramuloo", undercover: "Sarrainodu" },
      { civilian: "Vikram", undercover: "Kaithi" },
      { civilian: "Master", undercover: "Beast" },
      { civilian: "96", undercover: "Pariyerum Perumal" },
      { civilian: "Mersal", undercover: "Bigil" },
      { civilian: "Kabali", undercover: "Kaala" },
      { civilian: "Enthiran", undercover: "2.0" },
      { civilian: "Vinnaithaandi Varuvaayaa", undercover: "OK Kanmani" },
      { civilian: "Soorarai Pottru", undercover: "Jai Bhim" },
      { civilian: "Vikram Vedha", undercover: "Karthikeya 2" },
      { civilian: "HanuMan", undercover: "Kalki 2898 AD" },
      { civilian: "Salaar", undercover: "KGF" },
      { civilian: "Devara", undercover: "Leo" },
      { civilian: "Aranmanai", undercover: "Demonte Colony" },
      { civilian: "Jai Lava Kusa", undercover: "Temper" },
      { civilian: "Janatha Garage", undercover: "Agnyaathavaasi" },
      { civilian: "Nannaku Prematho", undercover: "S/O Satyamurthy" },
      { civilian: "Rangasthalam", undercover: "Fidaa" },
      { civilian: "Mahanati", undercover: "Maidaan" },
      { civilian: "Bimbisara", undercover: "Virupaksha" },
      { civilian: "Dasara", undercover: "Sardar" },
      { civilian: "Skanda", undercover: "Guntur Kaaram" },
      { civilian: "Pushpa 2", undercover: "Devara Part 1" },
      { civilian: "Saindhav", undercover: "Eagle" },
      { civilian: "Mufasa", undercover: "Dragon" },
      { civilian: "Super Deluxe", undercover: "Mandela" },
      { civilian: "Sarpatta Parambarai", undercover: "Karnan" },
      { civilian: "Koozhangal", undercover: "Anbarivu" },
      { civilian: "Ponniyin Selvan", undercover: "PS-2" },
      { civilian: "Mani Ratnam", undercover: "Shankar" },
      { civilian: "Selvaraghavan", undercover: "Pa Ranjith" },
      { civilian: "Suriya", undercover: "Vijay" },
      { civilian: "Ajith", undercover: "Dhanush" },
      { civilian: "Nayanthara", undercover: "Trisha" },
      { civilian: "Samantha", undercover: "Anushka Shetty" },
      { civilian: "Allu Arjun", undercover: "Ram Charan" },
      { civilian: "Mahesh Babu", undercover: "Prabhas" },
      { civilian: "NTR Jr", undercover: "Vijay Deverakonda" },
    ],
  },

  // ─────────────────────────────────────────────
  // SOUTH INDIAN FOOD
  // ─────────────────────────────────────────────
  {
    id: "south-food",
    name: "South Indian Food",
    emoji: "🍛",
    description: "Classic dishes from South India",
    pairs: [
      { civilian: "Dosa", undercover: "Uttapam" },
      { civilian: "Idli", undercover: "Vada" },
      { civilian: "Sambar", undercover: "Rasam" },
      { civilian: "Biryani", undercover: "Pulao" },
      { civilian: "Pongal", undercover: "Khichdi" },
      { civilian: "Appam", undercover: "Idiyappam" },
      { civilian: "Chettinad Curry", undercover: "Madras Curry" },
      { civilian: "Pesarattu", undercover: "Paniyaram" },
      { civilian: "Puttu", undercover: "String Hoppers" },
      { civilian: "Payasam", undercover: "Kheer" },
      { civilian: "Coconut Chutney", undercover: "Groundnut Chutney" },
      { civilian: "Filter Coffee", undercover: "Chai" },
      { civilian: "Murukku", undercover: "Chakli" },
      { civilian: "Hyderabadi Biryani", undercover: "Lucknowi Biryani" },
      { civilian: "Bisi Bele Bath", undercover: "Lemon Rice" },
      { civilian: "Medu Vada", undercover: "Bonda" },
      { civilian: "Avial", undercover: "Stir-Fried Vegetables" },
      { civilian: "Curd Rice", undercover: "Khichdi" },
      { civilian: "Banana Leaf Meal", undercover: "Thali" },
      { civilian: "Tamarind Rice", undercover: "Mango Rice" },
      { civilian: "Gunpowder Chutney", undercover: "Tomato Chutney" },
      { civilian: "Jaggery Payasam", undercover: "Semolina Halwa" },
      { civilian: "Sesame Laddu", undercover: "Peanut Brittle" },
      { civilian: "Masala Dosa", undercover: "Rava Dosa" },
      { civilian: "Paper Dosa", undercover: "Set Dosa" },
      { civilian: "Kuzhi Paniyaram", undercover: "Kolukattai" },
      { civilian: "Kozhukatta", undercover: "Ela Ada" },
      { civilian: "Meen Curry", undercover: "Prawn Masala" },
      { civilian: "Crab Curry", undercover: "Squid Fry" },
      { civilian: "Chicken Chettinad", undercover: "Mutton Kola Urundai" },
      { civilian: "Vazhaipoo Vadai", undercover: "Paruppu Vadai" },
      { civilian: "Sundal", undercover: "Kara Boondhi" },
      { civilian: "Mor Kuzhambu", undercover: "Vatha Kuzhambu" },
      { civilian: "Kootu", undercover: "Poriyal" },
      { civilian: "Thayir Sadam", undercover: "Kanji" },
      { civilian: "Kerala Prawn Curry", undercover: "Fish Molee" },
      { civilian: "Sadya", undercover: "Onam Feast" },
      { civilian: "Pachadi", undercover: "Olan" },
      { civilian: "Kaalan", undercover: "Erissery" },
      { civilian: "Puttu Kadala", undercover: "Appam Stew" },
      { civilian: "Parotta", undercover: "Kothu Parotta" },
      { civilian: "Kari Dosa", undercover: "Egg Dosa" },
      { civilian: "Upma", undercover: "Semiya Upma" },
      { civilian: "Poha", undercover: "Aval Vilayichathu" },
      { civilian: "Nei Choru", undercover: "Ghee Rice" },
    ],
  },

  // ─────────────────────────────────────────────
  // NORTH INDIAN FOOD
  // ─────────────────────────────────────────────
  {
    id: "north-food",
    name: "North Indian Food",
    emoji: "🫓",
    description: "Flavours from the North",
    pairs: [
      { civilian: "Butter Chicken", undercover: "Tandoori Chicken" },
      { civilian: "Naan", undercover: "Roti" },
      { civilian: "Rajma Chawal", undercover: "Dal Chawal" },
      { civilian: "Chole Bhature", undercover: "Puri Sabzi" },
      { civilian: "Paneer Tikka", undercover: "Chicken Tikka" },
      { civilian: "Lassi", undercover: "Chaas" },
      { civilian: "Kulfi", undercover: "Falooda" },
      { civilian: "Gajar Ka Halwa", undercover: "Moong Dal Halwa" },
      { civilian: "Samosa", undercover: "Kachori" },
      { civilian: "Gulab Jamun", undercover: "Rasgulla" },
      { civilian: "Paratha", undercover: "Rumali Roti" },
      { civilian: "Aloo Tikki", undercover: "Batata Vada" },
      { civilian: "Palak Paneer", undercover: "Saag Gosht" },
      { civilian: "Korma", undercover: "Nihari" },
      { civilian: "Jalebi", undercover: "Imarti" },
      { civilian: "Dal Makhani", undercover: "Chole Curry" },
      { civilian: "Seekh Kabab", undercover: "Galouti Kabab" },
      { civilian: "Saag Aloo", undercover: "Baingan Bharta" },
      { civilian: "Pav Bhaji", undercover: "Bhelpuri" },
      { civilian: "Matar Paneer", undercover: "Paneer Makhani" },
      { civilian: "Barfi", undercover: "Peda" },
      { civilian: "Bread Pakora", undercover: "Onion Pakora" },
      { civilian: "Shahi Tukda", undercover: "Double Ka Meetha" },
      { civilian: "Haleem", undercover: "Khichda" },
      { civilian: "Aloo Paratha", undercover: "Gobhi Paratha" },
      { civilian: "Mooli Paratha", undercover: "Pyaaz Paratha" },
      { civilian: "Makki ki Roti", undercover: "Bajre ki Roti" },
      { civilian: "Sarson ka Saag", undercover: "Bathua Saag" },
      { civilian: "Chana Dal", undercover: "Arhar Dal" },
      { civilian: "Sheermal", undercover: "Bakarkhani" },
      { civilian: "Phirni", undercover: "Kheer" },
      { civilian: "Sewai", undercover: "Muzaffar" },
      { civilian: "Thandai", undercover: "Sharbat" },
      { civilian: "Aam Panna", undercover: "Jaljeera" },
      { civilian: "Mathri", undercover: "Nimki" },
      { civilian: "Shakarpara", undercover: "Gujiya" },
      { civilian: "Pinni", undercover: "Til Chikki" },
      { civilian: "Khoya Barfi", undercover: "Kaju Katli" },
      { civilian: "Motichoor Ladoo", undercover: "Besan Ladoo" },
      { civilian: "Rabri", undercover: "Basundi" },
      { civilian: "Kulcha", undercover: "Amritsari Kulcha" },
      { civilian: "Rewari", undercover: "Gajak" },
    ],
  },

  // ─────────────────────────────────────────────
  // STREET FOOD
  // ─────────────────────────────────────────────
  {
    id: "street-food",
    name: "Desi Street Food",
    emoji: "🥘",
    description: "India's best street eats",
    pairs: [
      { civilian: "Pani Puri", undercover: "Sev Puri" },
      { civilian: "Vada Pav", undercover: "Dabeli" },
      { civilian: "Pav Bhaji", undercover: "Misal Pav" },
      { civilian: "Bhel Puri", undercover: "Aloo Chaat" },
      { civilian: "Kathi Roll", undercover: "Frankie" },
      { civilian: "Papdi Chaat", undercover: "Dahi Papdi" },
      { civilian: "Litti Chokha", undercover: "Bati Churma" },
      { civilian: "Egg Roll", undercover: "Paneer Roll" },
      { civilian: "Momos", undercover: "Dimsums" },
      { civilian: "Dahi Bhalle", undercover: "Dahi Vada" },
      { civilian: "Tikki Chaat", undercover: "Rajma Chaat" },
      { civilian: "Corn Chaat", undercover: "Masala Corn" },
      { civilian: "Falooda", undercover: "Rose Milk" },
      { civilian: "Kulhad Chai", undercover: "Tapri Chai" },
      { civilian: "Gol Gappa", undercover: "Batata Puri" },
      { civilian: "Ragda Pattice", undercover: "Sev Batata Puri" },
      { civilian: "Jhal Muri", undercover: "Churmur" },
      { civilian: "Pyaaz Pakora", undercover: "Mirch Pakora" },
      { civilian: "Corn Pakora", undercover: "Bread Pakora" },
      { civilian: "Egg Bhurji", undercover: "Paneer Bhurji" },
      { civilian: "Tawa Pulao", undercover: "Schezwan Fried Rice" },
      { civilian: "Keema Pav", undercover: "Chicken Frankie" },
      { civilian: "Bun Maska", undercover: "Irani Chai" },
      { civilian: "Baida Roti", undercover: "Rumali Roti Roll" },
      { civilian: "Sattu Sharbat", undercover: "Lassi" },
      { civilian: "Sugarcane Juice", undercover: "Nimbu Pani" },
      { civilian: "Kulfi Faluda", undercover: "Rabri Faluda" },
      { civilian: "Sevpuri", undercover: "Ragda Puri" },
      { civilian: "Stuffed Mirchi Bajji", undercover: "Aloo Bajji" },
      { civilian: "Punugulu", undercover: "Mullangi Bajji" },
      { civilian: "Boiled Chana", undercover: "Masala Peanuts" },
      { civilian: "Tandoori Chai", undercover: "Kulhad Coffee" },
      { civilian: "Lassi", undercover: "Mattha" },
      { civilian: "Poha Jalebi", undercover: "Upma Vada" },
      { civilian: "Kanda Poha", undercover: "Batata Poha" },
      { civilian: "Sabudana Vada", undercover: "Sabudana Khichdi" },
      { civilian: "Thela Gadi", undercover: "Rehri" },
      { civilian: "Momo Chili", undercover: "Momo Soup" },
      { civilian: "Churros", undercover: "Balushahi" },
      { civilian: "Ram Ladoo", undercover: "Chhole Kulche" },
    ],
  },

  // ─────────────────────────────────────────────
  // CRICKET
  // ─────────────────────────────────────────────
  {
    id: "cricket",
    name: "Cricket",
    emoji: "🏏",
    description: "India's religion",
    pairs: [
      { civilian: "Virat Kohli", undercover: "Rohit Sharma" },
      { civilian: "MS Dhoni", undercover: "Sourav Ganguly" },
      { civilian: "IPL", undercover: "T20 World Cup" },
      { civilian: "Test Match", undercover: "ODI" },
      { civilian: "Mumbai Indians", undercover: "Chennai Super Kings" },
      { civilian: "Eden Gardens", undercover: "Wankhede" },
      { civilian: "Yorker", undercover: "Bouncer" },
      { civilian: "Six", undercover: "Four" },
      { civilian: "LBW", undercover: "Bowled" },
      { civilian: "Sachin Tendulkar", undercover: "Brian Lara" },
      { civilian: "Jasprit Bumrah", undercover: "Mohammed Shami" },
      { civilian: "Spin Bowling", undercover: "Fast Bowling" },
      { civilian: "Cover Drive", undercover: "Square Cut" },
      { civilian: "DRS", undercover: "Hawkeye" },
      { civilian: "Powerplay", undercover: "Death Overs" },
      { civilian: "Suresh Raina", undercover: "Yuvraj Singh" },
      { civilian: "Anil Kumble", undercover: "Ravichandran Ashwin" },
      { civilian: "Ravindra Jadeja", undercover: "Kuldeep Yadav" },
      { civilian: "Shikhar Dhawan", undercover: "KL Rahul" },
      { civilian: "Hardik Pandya", undercover: "Rishabh Pant" },
      { civilian: "Stumped", undercover: "Caught Out" },
      { civilian: "Maiden Over", undercover: "Dot Ball" },
      { civilian: "Slip Fielding", undercover: "Gully Fielding" },
      { civilian: "Swing Bowling", undercover: "Seam Bowling" },
      { civilian: "Cricket World Cup", undercover: "Asia Cup" },
      { civilian: "Royal Challengers Bangalore", undercover: "Kolkata Knight Riders" },
      { civilian: "Delhi Capitals", undercover: "Punjab Kings" },
      { civilian: "Sunrisers Hyderabad", undercover: "Rajasthan Royals" },
      { civilian: "Lucknow Super Giants", undercover: "Gujarat Titans" },
      { civilian: "Chinnaswamy Stadium", undercover: "Narendra Modi Stadium" },
      { civilian: "Chepauk", undercover: "Feroz Shah Kotla" },
      { civilian: "Rajiv Gandhi Stadium", undercover: "Sawai Mansingh Stadium" },
      { civilian: "Sunil Gavaskar", undercover: "Kapil Dev" },
      { civilian: "Zaheer Khan", undercover: "Ishant Sharma" },
      { civilian: "V.V.S. Laxman", undercover: "Rahul Dravid" },
      { civilian: "Harbhajan Singh", undercover: "Pragyan Ojha" },
      { civilian: "Dinesh Karthik", undercover: "Sanju Samson" },
      { civilian: "Shreyas Iyer", undercover: "Shubman Gill" },
      { civilian: "Yashasvi Jaiswal", undercover: "Ruturaj Gaikwad" },
      { civilian: "Tilak Varma", undercover: "Rinku Singh" },
      { civilian: "Super Over", undercover: "Bowl-Out" },
      { civilian: "Duck", undercover: "Golden Duck" },
      { civilian: "Century", undercover: "Half Century" },
      { civilian: "Hat Trick", undercover: "Five-For" },
      { civilian: "Innings Break", undercover: "Drinks Break" },
    ],
  },

  // ─────────────────────────────────────────────
  // INDIAN CITIES
  // ─────────────────────────────────────────────
  {
    id: "cities",
    name: "Indian Cities",
    emoji: "🏙️",
    description: "From metros to hidden gems",
    pairs: [
      { civilian: "Mumbai", undercover: "Bangalore" },
      { civilian: "Hyderabad", undercover: "Secunderabad" },
      { civilian: "Chennai", undercover: "Coimbatore" },
      { civilian: "Delhi", undercover: "Gurugram" },
      { civilian: "Bengaluru", undercover: "Mysuru" },
      { civilian: "Kolkata", undercover: "Howrah" },
      { civilian: "Jaipur", undercover: "Udaipur" },
      { civilian: "Ahmedabad", undercover: "Surat" },
      { civilian: "Goa", undercover: "Pondicherry" },
      { civilian: "Varanasi", undercover: "Prayagraj" },
      { civilian: "Amritsar", undercover: "Ludhiana" },
      { civilian: "Kochi", undercover: "Thiruvananthapuram" },
      { civilian: "Visakhapatnam", undercover: "Vijayawada" },
      { civilian: "Shimla", undercover: "Nainital" },
      { civilian: "Lucknow", undercover: "Kanpur" },
      { civilian: "Indore", undercover: "Nagpur" },
      { civilian: "Chandigarh", undercover: "Mohali" },
      { civilian: "Pune", undercover: "Nashik" },
      { civilian: "Srinagar", undercover: "Leh" },
      { civilian: "Bhopal", undercover: "Gwalior" },
      { civilian: "Jamshedpur", undercover: "Raipur" },
      { civilian: "Ranchi", undercover: "Patna" },
      { civilian: "Bhubaneswar", undercover: "Cuttack" },
      { civilian: "Dehradun", undercover: "Haridwar" },
      { civilian: "Jodhpur", undercover: "Bikaner" },
      { civilian: "Agra", undercover: "Mathura" },
      { civilian: "Rishikesh", undercover: "Mussoorie" },
      { civilian: "Siliguri", undercover: "Darjeeling" },
      { civilian: "Guwahati", undercover: "Jorhat" },
      { civilian: "Imphal", undercover: "Aizawl" },
      { civilian: "Shillong", undercover: "Gangtok" },
      { civilian: "Thane", undercover: "Navi Mumbai" },
      { civilian: "Noida", undercover: "Faridabad" },
      { civilian: "Ghaziabad", undercover: "Meerut" },
      { civilian: "Madurai", undercover: "Tiruchirappalli" },
      { civilian: "Salem", undercover: "Erode" },
      { civilian: "Tirunelveli", undercover: "Thoothukudi" },
      { civilian: "Mangalore", undercover: "Hubli" },
      { civilian: "Belgaum", undercover: "Gulbarga" },
      { civilian: "Ajmer", undercover: "Pushkar" },
      { civilian: "Aligarh", undercover: "Moradabad" },
      { civilian: "Bareilly", undercover: "Gorakhpur" },
      { civilian: "Varanasi", undercover: "Ayodhya" },
      { civilian: "Tirupati", undercover: "Vijayawada" },
      { civilian: "Nellore", undercover: "Guntur" },
      { civilian: "Warangal", undercover: "Karimnagar" },
    ],
  },

  // ─────────────────────────────────────────────
  // FESTIVALS
  // ─────────────────────────────────────────────
  {
    id: "festivals",
    name: "Indian Festivals",
    emoji: "🪔",
    description: "Celebrations across India",
    pairs: [
      { civilian: "Diwali", undercover: "Dussehra" },
      { civilian: "Holi", undercover: "Basant Panchami" },
      { civilian: "Eid ul-Fitr", undercover: "Eid ul-Adha" },
      { civilian: "Pongal", undercover: "Makar Sankranti" },
      { civilian: "Onam", undercover: "Vishu" },
      { civilian: "Navratri", undercover: "Garba" },
      { civilian: "Ganesh Chaturthi", undercover: "Durga Puja" },
      { civilian: "Baisakhi", undercover: "Lohri" },
      { civilian: "Ugadi", undercover: "Gudi Padwa" },
      { civilian: "Bihu", undercover: "Assam Tea Festival" },
      { civilian: "Christmas", undercover: "Easter" },
      { civilian: "Janmashtami", undercover: "Ram Navami" },
      { civilian: "Raksha Bandhan", undercover: "Bhai Dooj" },
      { civilian: "Mahavir Jayanti", undercover: "Buddha Purnima" },
      { civilian: "Karva Chauth", undercover: "Maha Shivaratri" },
      { civilian: "Chhath Puja", undercover: "Kumbh Mela" },
      { civilian: "Holi Colors", undercover: "Holi Bonfire" },
      { civilian: "Teej", undercover: "Hartalika Teej" },
      { civilian: "Navaratri Garba", undercover: "Dandiya Raas" },
      { civilian: "Thrissur Pooram", undercover: "Nehru Trophy Boat Race" },
      { civilian: "Pushkar Fair", undercover: "Rann Utsav" },
      { civilian: "Hornbill Festival", undercover: "Chapchar Kut" },
      { civilian: "Hemis Festival", undercover: "Losar" },
      { civilian: "Puri Rath Yatra", undercover: "Jagannath Festival" },
      { civilian: "Makar Mela", undercover: "Gangasagar Mela" },
      { civilian: "Ambubachi Mela", undercover: "Dehing Patkai Festival" },
      { civilian: "Konark Dance Festival", undercover: "Khajuraho Festival" },
      { civilian: "Mysuru Dasara", undercover: "Hampi Utsav" },
      { civilian: "Pattadakal Festival", undercover: "Chitrakot Festival" },
      { civilian: "Taj Mahotsav", undercover: "Surajkund Mela" },
      { civilian: "International Mango Festival", undercover: "Rose Festival Chandigarh" },
      { civilian: "Muharram", undercover: "Milad-un-Nabi" },
      { civilian: "Guru Nanak Jayanti", undercover: "Guru Gobind Singh Jayanti" },
      { civilian: "Vaisakhi", undercover: "Holla Mohalla" },
      { civilian: "Diwali Puja", undercover: "Lakshmi Puja" },
    ],
  },

  // ─────────────────────────────────────────────
  // WEB SERIES
  // ─────────────────────────────────────────────
  {
    id: "web-series",
    name: "Indian Web Series",
    emoji: "📺",
    description: "OTT hits from India",
    pairs: [
      { civilian: "Mirzapur", undercover: "Panchayat" },
      { civilian: "Scam 1992", undercover: "Rocket Boys" },
      { civilian: "Sacred Games", undercover: "Delhi Crime" },
      { civilian: "Aspirants", undercover: "Kota Factory" },
      { civilian: "TVF Pitchers", undercover: "Shark Tank India" },
      { civilian: "Bandish Bandits", undercover: "Tabbar" },
      { civilian: "The Family Man", undercover: "Special Ops" },
      { civilian: "Four More Shots Please", undercover: "Girl in the City" },
      { civilian: "Breathe", undercover: "Hostages" },
      { civilian: "Made in Heaven", undercover: "Broken But Beautiful" },
      { civilian: "Jamtara", undercover: "Aranyak" },
      { civilian: "Aarya", undercover: "Bhaukaal" },
      { civilian: "Gullak", undercover: "Panchayat" },
      { civilian: "Criminal Justice", undercover: "Section 375" },
      { civilian: "Yeh Kaali Kaali Ankhein", undercover: "She" },
      { civilian: "Masaba Masaba", undercover: "The Trial" },
      { civilian: "Tandav", undercover: "Tanaav" },
      { civilian: "A Suitable Boy", undercover: "Paatal Lok" },
      { civilian: "Cobalt Blue", undercover: "Decoupled" },
      { civilian: "Kohrra", undercover: "Bambai Meri Jaan" },
      { civilian: "Dahaad", undercover: "Class" },
      { civilian: "Suzhal", undercover: "Vadhandhi" },
      { civilian: "Triples", undercover: "Comicstaan" },
      { civilian: "Scam 2003", undercover: "Scoop" },
      { civilian: "Guns & Gulaabs", undercover: "Farzi" },
      { civilian: "Gyaarah Gyaarah", undercover: "IC 814" },
      { civilian: "Phule", undercover: "Tribhuvan Mishra CA Topper" },
      { civilian: "Killer Soup", undercover: "Poacher" },
      { civilian: "Heeramandi", undercover: "Taj: Divided by Blood" },
      { civilian: "Panchayat 3", undercover: "Kota Factory 3" },
      { civilian: "Aspirants 2", undercover: "Hostel Daze" },
      { civilian: "Immature", undercover: "Please Find Attached" },
      { civilian: "Pitchers 2", undercover: "Yeh Meri Family" },
      { civilian: "Tripling", undercover: "Typewriter" },
      { civilian: "Breathe Into the Shadows", undercover: "Nail Polish" },
    ],
  },

  // ─────────────────────────────────────────────
  // BOLLYWOOD ACTORS
  // ─────────────────────────────────────────────
  {
    id: "actors",
    name: "Bollywood Actors",
    emoji: "🌟",
    description: "Stars of Hindi cinema",
    pairs: [
      { civilian: "Shah Rukh Khan", undercover: "Salman Khan" },
      { civilian: "Deepika Padukone", undercover: "Priyanka Chopra" },
      { civilian: "Ranveer Singh", undercover: "Ranbir Kapoor" },
      { civilian: "Alia Bhatt", undercover: "Katrina Kaif" },
      { civilian: "Amitabh Bachchan", undercover: "Dharmendra" },
      { civilian: "Ayushmann Khurrana", undercover: "Rajkummar Rao" },
      { civilian: "Taapsee Pannu", undercover: "Bhumi Pednekar" },
      { civilian: "Prabhas", undercover: "Allu Arjun" },
      { civilian: "Vijay Deverakonda", undercover: "Kartik Aaryan" },
      { civilian: "Kangana Ranaut", undercover: "Vidya Balan" },
      { civilian: "Nawazuddin Siddiqui", undercover: "Manoj Bajpayee" },
      { civilian: "Hrithik Roshan", undercover: "Tiger Shroff" },
      { civilian: "Akshay Kumar", undercover: "Ajay Devgn" },
      { civilian: "Varun Dhawan", undercover: "Siddhant Chaturvedi" },
      { civilian: "Janhvi Kapoor", undercover: "Sara Ali Khan" },
      { civilian: "Ananya Panday", undercover: "Rakul Preet Singh" },
      { civilian: "Sidharth Malhotra", undercover: "Arjun Kapoor" },
      { civilian: "Emraan Hashmi", undercover: "John Abraham" },
      { civilian: "Kareena Kapoor", undercover: "Karisma Kapoor" },
      { civilian: "Aishwarya Rai", undercover: "Madhuri Dixit" },
      { civilian: "Jacqueline Fernandez", undercover: "Disha Patani" },
      { civilian: "Bobby Deol", undercover: "Sunny Deol" },
      { civilian: "Rishi Kapoor", undercover: "Jeetendra" },
      { civilian: "Farhan Akhtar", undercover: "Abhay Deol" },
      { civilian: "Irrfan Khan", undercover: "Naseeruddin Shah" },
      { civilian: "Pankaj Tripathi", undercover: "Rajpal Yadav" },
      { civilian: "Boman Irani", undercover: "Paresh Rawal" },
      { civilian: "Anupam Kher", undercover: "Om Puri" },
      { civilian: "Dimple Kapadia", undercover: "Hema Malini" },
      { civilian: "Rekha", undercover: "Sridevi" },
      { civilian: "Juhi Chawla", undercover: "Revathi" },
      { civilian: "Konkona Sen Sharma", undercover: "Kalki Koechlin" },
      { civilian: "Swara Bhasker", undercover: "Radhika Apte" },
      { civilian: "Shefali Shah", undercover: "Tillotama Shome" },
      { civilian: "Nora Fatehi", undercover: "Malaika Arora" },
      { civilian: "Divyenndu", undercover: "Ali Fazal" },
    ],
  },

  // ─────────────────────────────────────────────
  // NEW: INDIAN MUSIC
  // ─────────────────────────────────────────────
  {
    id: "indian-music",
    name: "Indian Music",
    emoji: "🎵",
    description: "Beats from Bollywood to indie",
    pairs: [
      { civilian: "Arijit Singh", undercover: "Atif Aslam" },
      { civilian: "A.R. Rahman", undercover: "Shankar Ehsaan Loy" },
      { civilian: "Shreya Ghoshal", undercover: "Sunidhi Chauhan" },
      { civilian: "Sonu Nigam", undercover: "Udit Narayan" },
      { civilian: "Kumar Sanu", undercover: "Mohammed Aziz" },
      { civilian: "Lata Mangeshkar", undercover: "Asha Bhosle" },
      { civilian: "Kishore Kumar", undercover: "Mohammed Rafi" },
      { civilian: "Nucleya", undercover: "Ritviz" },
      { civilian: "Divine", undercover: "Naezy" },
      { civilian: "Prateek Kuhad", undercover: "Ankur Tewari" },
      { civilian: "When She Sleeps", undercover: "The Local Train" },
      { civilian: "Indian Ocean", undercover: "Euphoria" },
      { civilian: "Papon", undercover: "Kailash Kher" },
      { civilian: "Hariharan", undercover: "Shankar Mahadevan" },
      { civilian: "Vishal Bhardwaj", undercover: "Pritam" },
      { civilian: "Anu Malik", undercover: "Himesh Reshammiya" },
      { civilian: "Daler Mehndi", undercover: "Gurdas Maan" },
      { civilian: "Hans Raj Hans", undercover: "Malkit Singh" },
      { civilian: "Usha Uthup", undercover: "Kavita Krishnamurthy" },
      { civilian: "S.P. Balasubrahmanyam", undercover: "K.J. Yesudas" },
      { civilian: "Ilayaraja", undercover: "A.R. Rahman" },
      { civilian: "Yuvan Shankar Raja", undercover: "D. Imman" },
      { civilian: "Anirudh Ravichander", undercover: "Thaman S" },
      { civilian: "Vishal-Shekhar", undercover: "Meet Bros" },
      { civilian: "Badshah", undercover: "Yo Yo Honey Singh" },
      { civilian: "AP Dhillon", undercover: "Shubh" },
      { civilian: "Sidhu Moosewala", undercover: "Amrit Maan" },
      { civilian: "Guru Randhawa", undercover: "Hardy Sandhu" },
      { civilian: "Neha Kakkar", undercover: "Tulsi Kumar" },
      { civilian: "Armaan Malik", undercover: "Darshan Raval" },
      { civilian: "Jubin Nautiyal", undercover: "B Praak" },
      { civilian: "Stebin Ben", undercover: "Vishal Mishra" },
      { civilian: "Alka Yagnik", undercover: "Kavita Subramaniam" },
      { civilian: "Rahat Fateh Ali Khan", undercover: "Nusrat Fateh Ali Khan" },
      { civilian: "Karunesh", undercover: "Ravi Shankar" },
    ],
  },

  // ─────────────────────────────────────────────
  // NEW: INDIAN TV SHOWS
  // ─────────────────────────────────────────────
  {
    id: "indian-tv",
    name: "Indian TV Shows",
    emoji: "📡",
    description: "Doordarshan to daily soaps",
    pairs: [
      { civilian: "Ramayan", undercover: "Mahabharat" },
      { civilian: "Kyunki Saas Bhi Kabhi Bahu Thi", undercover: "Kasautii Zindagi Kay" },
      { civilian: "Taarak Mehta Ka Ooltah Chashmah", undercover: "Bhabiji Ghar Par Hai" },
      { civilian: "Kaun Banega Crorepati", undercover: "Bigg Boss" },
      { civilian: "Indian Idol", undercover: "Sa Re Ga Ma Pa" },
      { civilian: "Dance India Dance", undercover: "Jhalak Dikhhla Jaa" },
      { civilian: "Comedy Nights with Kapil", undercover: "The Kapil Sharma Show" },
      { civilian: "CID", undercover: "Crime Patrol" },
      { civilian: "Savdhaan India", undercover: "India's Most Wanted" },
      { civilian: "Balika Vadhu", undercover: "Anupamaa" },
      { civilian: "Yeh Hai Mohabbatein", undercover: "Yeh Rishta Kya Kehlata Hai" },
      { civilian: "Naagin", undercover: "Brahmarakshas" },
      { civilian: "Shakti", undercover: "Udaariyaan" },
      { civilian: "Pehredaar Piya Ki", undercover: "Tujhse Hai Raabta" },
      { civilian: "Pavitra Rishta", undercover: "Dill Mill Gayye" },
      { civilian: "Jassi Jaissi Koi Nahin", undercover: "Remix" },
      { civilian: "Shaktimaan", undercover: "Captain Vyom" },
      { civilian: "Malgudi Days", undercover: "Byomkesh Bakshi" },
      { civilian: "Jungle Book DD", undercover: "Giant Robot" },
      { civilian: "Dekh Bhai Dekh", undercover: "Hum Paanch" },
      { civilian: "Hip Hip Hurray", undercover: "Just Mohabbat" },
      { civilian: "Saans", undercover: "Junoon" },
      { civilian: "Fauji", undercover: "Circus" },
      { civilian: "Chitrahaar", undercover: "Rangoli" },
      { civilian: "Star Plus", undercover: "Sony Entertainment" },
      { civilian: "Colors TV", undercover: "Zee TV" },
      { civilian: "Sun TV", undercover: "Vijay TV" },
      { civilian: "Asianet", undercover: "Surya TV" },
      { civilian: "ETV Telugu", undercover: "Maa TV" },
      { civilian: "Gemini TV", undercover: "Zee Telugu" },
    ],
  },

  // ─────────────────────────────────────────────
  // NEW: INDIAN SWEETS & DESSERTS
  // ─────────────────────────────────────────────
  {
    id: "indian-sweets",
    name: "Indian Sweets",
    emoji: "🍮",
    description: "Mithai from every corner of India",
    pairs: [
      { civilian: "Gulab Jamun", undercover: "Rasgulla" },
      { civilian: "Jalebi", undercover: "Imarti" },
      { civilian: "Barfi", undercover: "Peda" },
      { civilian: "Kaju Katli", undercover: "Kaju Roll" },
      { civilian: "Ladoo", undercover: "Modak" },
      { civilian: "Halwa", undercover: "Sheera" },
      { civilian: "Kheer", undercover: "Phirni" },
      { civilian: "Rasmalai", undercover: "Rajbhog" },
      { civilian: "Sandesh", undercover: "Chum Chum" },
      { civilian: "Mishti Doi", undercover: "Bhapa Doi" },
      { civilian: "Ledikeni", undercover: "Pantua" },
      { civilian: "Payesh", undercover: "Sitabhog" },
      { civilian: "Mysore Pak", undercover: "Dharwad Peda" },
      { civilian: "Chiroti", undercover: "Kadubu" },
      { civilian: "Holige", undercover: "Malpua" },
      { civilian: "Adhirasam", undercover: "Sakkarai Pongal" },
      { civilian: "Tirunelveli Halwa", undercover: "Kozhikodan Halwa" },
      { civilian: "Unniyappam", undercover: "Achappam" },
      { civilian: "Ariselu", undercover: "Boorelu" },
      { civilian: "Putharekulu", undercover: "Arikalu" },
      { civilian: "Kajjikayalu", undercover: "Gavvalu" },
      { civilian: "Shrikhand", undercover: "Basundi" },
      { civilian: "Mohanthal", undercover: "Sutarfeni" },
      { civilian: "Ghari", undercover: "Ghughra" },
      { civilian: "Panjiri", undercover: "Pinni" },
      { civilian: "Khaja", undercover: "Balushahi" },
      { civilian: "Tilkut", undercover: "Khajuria" },
      { civilian: "Thekua", undercover: "Khurma" },
      { civilian: "Petha", undercover: "Rewdi" },
      { civilian: "Gajak", undercover: "Chikki" },
    ],
  },

  // ─────────────────────────────────────────────
  // NEW: INDIAN LANGUAGES
  // ─────────────────────────────────────────────
  {
    id: "indian-languages",
    name: "Indian Languages",
    emoji: "🗣️",
    description: "India's linguistic diversity",
    pairs: [
      { civilian: "Hindi", undercover: "Urdu" },
      { civilian: "Tamil", undercover: "Malayalam" },
      { civilian: "Telugu", undercover: "Kannada" },
      { civilian: "Bengali", undercover: "Odia" },
      { civilian: "Marathi", undercover: "Gujarati" },
      { civilian: "Punjabi", undercover: "Haryanvi" },
      { civilian: "Bhojpuri", undercover: "Maithili" },
      { civilian: "Rajasthani", undercover: "Mewari" },
      { civilian: "Sindhi", undercover: "Kutchi" },
      { civilian: "Assamese", undercover: "Bodo" },
      { civilian: "Manipuri", undercover: "Mizo" },
      { civilian: "Nagamese", undercover: "Khasi" },
      { civilian: "Konkani", undercover: "Tulu" },
      { civilian: "Kashmiri", undercover: "Dogri" },
      { civilian: "Sanskrit", undercover: "Pali" },
      { civilian: "Awadhi", undercover: "Braj Bhasha" },
      { civilian: "Chhattisgarhi", undercover: "Gondi" },
      { civilian: "Santhali", undercover: "Mundari" },
      { civilian: "Nepali", undercover: "Tibetan" },
      { civilian: "Devanagari", undercover: "Gurmukhi" },
      { civilian: "Tamil Script", undercover: "Telugu Script" },
      { civilian: "Bengali Script", undercover: "Odia Script" },
    ],
  },

  // ─────────────────────────────────────────────
  // NEW: INDIAN SPORTS (NON-CRICKET)
  // ─────────────────────────────────────────────
  {
    id: "indian-sports",
    name: "Indian Sports",
    emoji: "🏅",
    description: "Beyond cricket",
    pairs: [
      { civilian: "Kabaddi", undercover: "Kho Kho" },
      { civilian: "Badminton", undercover: "Squash" },
      { civilian: "Hockey", undercover: "Football" },
      { civilian: "Wrestling", undercover: "Boxing" },
      { civilian: "Chess", undercover: "Carrom" },
      { civilian: "Shooting", undercover: "Archery" },
      { civilian: "Weightlifting", undercover: "Javelin" },
      { civilian: "PV Sindhu", undercover: "Saina Nehwal" },
      { civilian: "Neeraj Chopra", undercover: "Anju Bobby George" },
      { civilian: "Mary Kom", undercover: "Nikhat Zareen" },
      { civilian: "Bajrang Punia", undercover: "Vinesh Phogat" },
      { civilian: "Abhinav Bindra", undercover: "Rajyavardhan Rathore" },
      { civilian: "Sunil Chhetri", undercover: "Bhaichung Bhutia" },
      { civilian: "Dhyan Chand", undercover: "Udham Singh" },
      { civilian: "Pro Kabaddi League", undercover: "Ultimate Kho Kho" },
      { civilian: "ISL", undercover: "I-League" },
      { civilian: "Premier Badminton League", undercover: "UTT Table Tennis" },
      { civilian: "PKL", undercover: "Super Cup" },
      { civilian: "Leander Paes", undercover: "Mahesh Bhupathi" },
      { civilian: "Sania Mirza", undercover: "Ankita Raina" },
      { civilian: "Viswanathan Anand", undercover: "Koneru Humpy" },
      { civilian: "Deepa Karmakar", undercover: "Dipa Karmakar" },
      { civilian: "Karnam Malleswari", undercover: "Mirabai Chanu" },
      { civilian: "Lovlina Borgohain", undercover: "Pooja Rani" },
      { civilian: "Dutee Chand", undercover: "Hima Das" },
    ],
  },

  // ─────────────────────────────────────────────
  // NEW: INDIAN POLITICIANS
  // ─────────────────────────────────────────────
  {
    id: "indian-politics",
    name: "Indian Politics",
    emoji: "🏛️",
    description: "Leaders who shaped India",
    pairs: [
      { civilian: "Narendra Modi", undercover: "Amit Shah" },
      { civilian: "Rahul Gandhi", undercover: "Priyanka Gandhi" },
      { civilian: "Arvind Kejriwal", undercover: "Manish Sisodia" },
      { civilian: "Mamata Banerjee", undercover: "Abhishek Banerjee" },
      { civilian: "Yogi Adityanath", undercover: "Shivraj Singh Chouhan" },
      { civilian: "Chandrashekhar Rao", undercover: "Revanth Reddy" },
      { civilian: "Uddhav Thackeray", undercover: "Eknath Shinde" },
      { civilian: "Sharad Pawar", undercover: "Ajit Pawar" },
      { civilian: "Nitish Kumar", undercover: "Tejashwi Yadav" },
      { civilian: "Lalu Prasad Yadav", undercover: "Ram Vilas Paswan" },
      { civilian: "Naveen Patnaik", undercover: "Mohan Majhi" },
      { civilian: "Hemant Soren", undercover: "Champai Soren" },
      { civilian: "MK Stalin", undercover: "Edappadi Palaniswami" },
      { civilian: "Jayalalithaa", undercover: "Karunanidhi" },
      { civilian: "Siddaramaiah", undercover: "HD Kumaraswamy" },
      { civilian: "Pinarayi Vijayan", undercover: "Oommen Chandy" },
      { civilian: "Jawaharlal Nehru", undercover: "Sardar Patel" },
      { civilian: "Indira Gandhi", undercover: "Rajiv Gandhi" },
      { civilian: "Atal Bihari Vajpayee", undercover: "LK Advani" },
      { civilian: "Manmohan Singh", undercover: "P.V. Narasimha Rao" },
      { civilian: "APJ Abdul Kalam", undercover: "K.R. Narayanan" },
      { civilian: "Pranab Mukherjee", undercover: "Pratibha Patil" },
      { civilian: "BR Ambedkar", undercover: "Ram Manohar Lohia" },
    ],
  },

  // ─────────────────────────────────────────────
  // NEW: INDIAN FASHION
  // ─────────────────────────────────────────────
  {
    id: "indian-fashion",
    name: "Indian Fashion",
    emoji: "👗",
    description: "Threads and textiles of India",
    pairs: [
      { civilian: "Saree", undercover: "Lehenga" },
      { civilian: "Kurta", undercover: "Sherwani" },
      { civilian: "Salwar Kameez", undercover: "Churidar" },
      { civilian: "Dupatta", undercover: "Odhni" },
      { civilian: "Bandhani", undercover: "Ikat" },
      { civilian: "Banarasi Silk", undercover: "Kanjeevaram Silk" },
      { civilian: "Phulkari", undercover: "Chikankari" },
      { civilian: "Zari", undercover: "Gota Patti" },
      { civilian: "Kalamkari", undercover: "Madhubani Print" },
      { civilian: "Ajrakh", undercover: "Dabu Print" },
      { civilian: "Pashmina", undercover: "Kani Shawl" },
      { civilian: "Patola", undercover: "Pochampally" },
      { civilian: "Brocade", undercover: "Georgette" },
      { civilian: "Chanderi", undercover: "Maheshwari" },
      { civilian: "Tussar Silk", undercover: "Muga Silk" },
      { civilian: "Mundu", undercover: "Dhoti" },
      { civilian: "Angavastram", undercover: "Pheta" },
      { civilian: "Jodhpuri Suit", undercover: "Nawabi Achkan" },
      { civilian: "Sabyasachi", undercover: "Manish Malhotra" },
      { civilian: "Anita Dongre", undercover: "Tarun Tahiliani" },
      { civilian: "Rohit Bal", undercover: "Rajesh Pratap Singh" },
      { civilian: "Jhumka", undercover: "Kundan Necklace" },
      { civilian: "Maang Tikka", undercover: "Nath" },
      { civilian: "Bangles", undercover: "Kadas" },
      { civilian: "Kolhapuri Chappals", undercover: "Mojari" },
    ],
  },

  // ─────────────────────────────────────────────
  // NEW: DESI SCHOOL / COLLEGE LIFE
  // ─────────────────────────────────────────────
  {
    id: "desi-school",
    name: "Desi School Life",
    emoji: "🎒",
    description: "The Indian school experience",
    pairs: [
      { civilian: "IIT", undercover: "NIT" },
      { civilian: "JEE", undercover: "NEET" },
      { civilian: "CBSE", undercover: "ICSE" },
      { civilian: "Tuition", undercover: "Coaching" },
      { civilian: "Tiffin Box", undercover: "School Canteen" },
      { civilian: "PT Period", undercover: "Library Period" },
      { civilian: "Class Monitor", undercover: "Prefect" },
      { civilian: "Annual Day", undercover: "Sports Day" },
      { civilian: "Farewell", undercover: "Fresher's Party" },
      { civilian: "Attendance Proxy", undercover: "Bunking" },
      { civilian: "Parent-Teacher Meeting", undercover: "Report Card Day" },
      { civilian: "Board Exams", undercover: "Unit Test" },
      { civilian: "Marks vs Marks", undercover: "Grades vs Grades" },
      { civilian: "First Bench", undercover: "Last Bench" },
      { civilian: "School Prayer", undercover: "National Anthem" },
      { civilian: "Midday Meal", undercover: "Akshaya Patra" },
      { civilian: "Navodaya Vidyalaya", undercover: "Kendriya Vidyalaya" },
      { civilian: "DPS", undercover: "Ryan International" },
      { civilian: "Kota Factory", undercover: "Allen Institute" },
      { civilian: "UPSC", undercover: "State PSC" },
      { civilian: "CAT Exam", undercover: "GMAT" },
      { civilian: "IIM", undercover: "XLRI" },
      { civilian: "Law Entrance", undercover: "CLAT" },
      { civilian: "Hostel Life", undercover: "PG Life" },
      { civilian: "Roommate", undercover: "Wingmate" },
    ],
  },

  // ─────────────────────────────────────────────
  // NEW: DESI WEDDINGS
  // ─────────────────────────────────────────────
  {
    id: "desi-weddings",
    name: "Desi Weddings",
    emoji: "💒",
    description: "Shaadi season madness",
    pairs: [
      { civilian: "Mehndi", undercover: "Haldi" },
      { civilian: "Sangeet", undercover: "Cocktail Party" },
      { civilian: "Baraat", undercover: "Nikah" },
      { civilian: "Pheras", undercover: "Saptapadi" },
      { civilian: "Bidaai", undercover: "Sagai" },
      { civilian: "Mangalsutra", undercover: "Sindoor" },
      { civilian: "Mandap", undercover: "Shamiyana" },
      { civilian: "Wedding Planner", undercover: "Pandit Ji" },
      { civilian: "Band Baja Barat", undercover: "DJ Night" },
      { civilian: "Lehnga Choli", undercover: "Saree Draping" },
      { civilian: "Sherwani", undercover: "Bandhgala" },
      { civilian: "Joota Chupai", undercover: "Dahi Handi" },
      { civilian: "Kaale Teekey", undercover: "Nazar Battu" },
      { civilian: "Swayamvar", undercover: "Arranged Marriage" },
      { civilian: "Roka Ceremony", undercover: "Sagai" },
      { civilian: "Tilak Ceremony", undercover: "Shagun" },
      { civilian: "Wedding Caterers", undercover: "Halwai" },
      { civilian: "Buffet Dinner", undercover: "Bhandara" },
      { civilian: "Wedding Photographer", undercover: "Videographer" },
      { civilian: "Destination Wedding", undercover: "Backyard Shaadi" },
      { civilian: "Udaipur Wedding", undercover: "Goa Wedding" },
      { civilian: "Flower Decoration", undercover: "Marigold Decoration" },
      { civilian: "Gulab Jamun Counter", undercover: "Paan Counter" },
      { civilian: "Relatives You Haven't Seen", undercover: "Neighbours You Forgot" },
      { civilian: "Card Wedding", undercover: "Digital Invitation" },
    ],
  },

  // ─────────────────────────────────────────────
  // NEW: REGIONAL INDIAN COMMUNITIES
  // ─────────────────────────────────────────────
  {
    id: "regional-india",
    name: "Regional India",
    emoji: "🗺️",
    description: "Culture, customs & quirks by region",
    pairs: [
      { civilian: "Punjabi", undercover: "Haryanvi" },
      { civilian: "Marwari", undercover: "Sindhi" },
      { civilian: "Gujarati", undercover: "Kutchi" },
      { civilian: "Parsi", undercover: "Bohra" },
      { civilian: "Bengali", undercover: "Bihari" },
      { civilian: "Madrasi", undercover: "Tamilian" },
      { civilian: "Mallu", undercover: "Kannadiga" },
      { civilian: "Telugu", undercover: "Andhra" },
      { civilian: "Konkani", undercover: "Mangalorean" },
      { civilian: "Goan", undercover: "Kashmiri Pandit" },
      { civilian: "Nepali", undercover: "Assamese" },
      { civilian: "Mizo", undercover: "Naga" },
      { civilian: "Manipuri", undercover: "Meghalayan" },
      { civilian: "Odia", undercover: "Chhattisgarhi" },
      { civilian: "Jat", undercover: "Gujjar" },
      { civilian: "Yadav", undercover: "Kurmi" },
      { civilian: "Brahmin", undercover: "Kshatriya" },
      { civilian: "Nair", undercover: "Namboothiri" },
      { civilian: "Mudaliar", undercover: "Naidu" },
      { civilian: "Iyer", undercover: "Iyengar" },
      { civilian: "Bunt", undercover: "Billava" },
      { civilian: "Coorgi", undercover: "Kodava" },
      { civilian: "Rajput", undercover: "Maratha" },
      { civilian: "Ahir", undercover: "Lodha" },
      { civilian: "Dogra", undercover: "Gaddis" },
    ],
  },

  // ─────────────────────────────────────────────
  // NEW: INDIA TRAVEL & LANDMARKS
  // ─────────────────────────────────────────────
  {
    id: "india-travel",
    name: "India Travel",
    emoji: "✈️",
    description: "Must-see landmarks & destinations",
    pairs: [
      { civilian: "Taj Mahal", undercover: "Qutub Minar" },
      { civilian: "Red Fort", undercover: "Agra Fort" },
      { civilian: "Hampi", undercover: "Belur" },
      { civilian: "Mysore Palace", undercover: "Jai Vilas Palace" },
      { civilian: "Charminar", undercover: "Golconda Fort" },
      { civilian: "Meenakshi Temple", undercover: "Brihadeeswarar Temple" },
      { civilian: "Konark Sun Temple", undercover: "Jagannath Temple" },
      { civilian: "Khajuraho", undercover: "Ajanta Ellora" },
      { civilian: "Hawa Mahal", undercover: "City Palace Jaipur" },
      { civilian: "Mehrangarh Fort", undercover: "Amer Fort" },
      { civilian: "Backwaters Kerala", undercover: "Munnar" },
      { civilian: "Varkala", undercover: "Kovalam" },
      { civilian: "Andaman Islands", undercover: "Lakshadweep" },
      { civilian: "Valley of Flowers", undercover: "Kedarnath" },
      { civilian: "Ladakh", undercover: "Spiti Valley" },
      { civilian: "Manali", undercover: "Kasol" },
      { civilian: "Darjeeling", undercover: "Gangtok" },
      { civilian: "Kaziranga", undercover: "Sundarbans" },
      { civilian: "Jim Corbett", undercover: "Ranthambore" },
      { civilian: "Dudhwa", undercover: "Bandipur" },
      { civilian: "Coorg", undercover: "Ooty" },
      { civilian: "Pondicherry", undercover: "Mahabalipuram" },
      { civilian: "Golden Temple", undercover: "Durgiana Temple" },
      { civilian: "Vaishno Devi", undercover: "Amarnath" },
      { civilian: "Char Dham", undercover: "Panch Kedar" },
    ],
  },

  // ─────────────────────────────────────────────
  // NEW: DESI MEMES & POP CULTURE
  // ─────────────────────────────────────────────
  {
    id: "desi-memes",
    name: "Desi Memes & Pop Culture",
    emoji: "😂",
    description: "Internet India in full form",
    pairs: [
      { civilian: "Rasode Mein Kaun Tha", undercover: "Thodi Si Jo Pee Li Hai" },
      { civilian: "PUBG Mobile", undercover: "Free Fire" },
      { civilian: "Carry Minati", undercover: "Bb Ki Vines" },
      { civilian: "Bhuvan Bam", undercover: "Ashish Chanchlani" },
      { civilian: "Technical Guruji", undercover: "Trakin Tech" },
      { civilian: "Koffee With Karan", undercover: "Aap Ki Adalat" },
      { civilian: "Roadies", undercover: "Splitsvilla" },
      { civilian: "Bigg Boss Hindi", undercover: "Bigg Boss Tamil" },
      { civilian: "Kaun Banega Crorepati", undercover: "Deal Ya No Deal" },
      { civilian: "Indian Matchmaking", undercover: "Fabulous Lives" },
      { civilian: "Shark Tank India", undercover: "Dragon's Den India" },
      { civilian: "Neha Dhupia Squad", undercover: "Lilly Singh" },
      { civilian: "Bade Chote", undercover: "Chota Bheem" },
      { civilian: "Doraemon", undercover: "Shinchan" },
      { civilian: "Motu Patlu", undercover: "Oggy and the Cockroaches" },
      { civilian: "Jughead Jones", undercover: "Chacha Chaudhary" },
      { civilian: "Tinkle Comics", undercover: "Champak" },
      { civilian: "Sawal Hi Jawab Hai", undercover: "Ek Se Badhkar Ek" },
      { civilian: "Sarkari Result", undercover: "IndiaResult" },
      { civilian: "WhatsApp University", undercover: "Facebook Forwards" },
      { civilian: "Jio", undercover: "Airtel" },
      { civilian: "UPI", undercover: "Paytm" },
      { civilian: "Zomato", undercover: "Swiggy" },
      { civilian: "Ola", undercover: "Uber India" },
      { civilian: "Meesho", undercover: "Snapdeal" },
    ],
  },

  // ─────────────────────────────────────────────
  // NEW: DESI PARENTS QUOTES
  // ─────────────────────────────────────────────
  {
    id: "desi-parents",
    name: "Desi Parent Mode",
    emoji: "👨‍👩‍👧",
    description: "Classic things desi parents say",
    pairs: [
      { civilian: "Padhai kar", undercover: "Doctor ban" },
      { civilian: "Engineer ya Doctor", undercover: "Lawyer ya CA" },
      { civilian: "Log kya kahenge", undercover: "Khandaan ki izzat" },
      { civilian: "Shaadi kab karoge", undercover: "Bacche kab honge" },
      { civilian: "Hamare zamaane mein", undercover: "Tumhare baap ne" },
      { civilian: "Bijli mat barbad karo", undercover: "Paani mat waste karo" },
      { civilian: "Relatives aa rahe hain", undercover: "Dress theek kar" },
      { civilian: "Maths tuition", undercover: "Science coaching" },
      { civilian: "Mobile chhodo", undercover: "Bahar khelo" },
      { civilian: "Subah uthna chahiye", undercover: "Raat ko mat jago" },
      { civilian: "Naukri pehle", undercover: "Passion baad mein" },
      { civilian: "Sarkari naukri", undercover: "PSU job" },
      { civilian: "Beta settle ho jao", undercover: "Ghar lelo pehle" },
      { civilian: "Vegetarian khao", undercover: "Ghar ka khana" },
      { civilian: "Rishtedar ka beta", undercover: "Neighbourhood kid" },
      { civilian: "95% nahi 100% chahiye", undercover: "Top rank lao" },
      { civilian: "Thoda adjust karo", undercover: "Compromise seekho" },
      { civilian: "Ghar jaana zaroori hai", undercover: "Curfew time" },
      { civilian: "Pehle permission", undercover: "Pehle bolo toh" },
      { civilian: "Credit card mat use karo", undercover: "EMI mat lo" },
    ],
  },

  // ─────────────────────────────────────────────
  // NEW: BOLLYWOOD SONGS
  // ─────────────────────────────────────────────
  {
    id: "bollywood-songs",
    name: "Bollywood Songs",
    emoji: "🎶",
    description: "Iconic songs from Hindi films",
    pairs: [
      { civilian: "Tum Hi Ho", undercover: "Teri Mitti" },
      { civilian: "Chaiyya Chaiyya", undercover: "Jai Ho" },
      { civilian: "Rang De Basanti", undercover: "Ae Watan" },
      { civilian: "Dil Dhadakne Do", undercover: "Galliyan" },
      { civilian: "Kesariya", undercover: "Raataan Lambiyan" },
      { civilian: "Apna Time Aayega", undercover: "Mere Gully Mein" },
      { civilian: "Besharam Rang", undercover: "Jhoome Jo Pathaan" },
      { civilian: "Naatu Naatu", undercover: "Komuram Bheemudo" },
      { civilian: "Srivalli", undercover: "Oo Antava" },
      { civilian: "Pushpa Pushpa", undercover: "Kissik" },
      { civilian: "Kala Chashma", undercover: "Morni Banke" },
      { civilian: "Badtameez Dil", undercover: "Ghungroo" },
      { civilian: "Dilbar", undercover: "Kamariya" },
      { civilian: "Tip Tip Barsa Paani", undercover: "Chikni Chameli" },
      { civilian: "Kajra Re", undercover: "Bole Chudiyan" },
      { civilian: "Lag Ja Gale", undercover: "Tere Bina" },
      { civilian: "Kal Ho Naa Ho", undercover: "Kabhi Alvida Naa Kehna" },
      { civilian: "Pehla Nasha", undercover: "Pehli Baar Mohabbat" },
      { civilian: "Kuch Kuch Hota Hai", undercover: "Tujhe Yaad Na Meri Aaye" },
      { civilian: "Dil To Pagal Hai", undercover: "Hai Rama" },
      { civilian: "Aashiqui 2 Theme", undercover: "Sun Raha Hai Na Tu" },
      { civilian: "Channa Mereya", undercover: "Bulleya" },
      { civilian: "Ae Dil Hai Mushkil", undercover: "Hawayein" },
      { civilian: "Tujh Mein Rab Dikhta Hai", undercover: "Tere Haath Mein" },
      { civilian: "Jai Jai Shiv Shankar", undercover: "Bam Bhole" },
    ],
  },
];

export function getRandomPair(packId: string): WordPair {
  const pack = WORD_PACKS.find((p) => p.id === packId);
  if (!pack) return { civilian: "Dosa", undercover: "Uttapam" };
  return pack.pairs[Math.floor(Math.random() * pack.pairs.length)];
}

export function getPackById(packId: string): WordPack | undefined {
  return WORD_PACKS.find((p) => p.id === packId);
}