export interface WordPair {
  word1: string;
  word2: string;
}

export type GameId = "wordspy" | "pictionary" | "dumbcharades";

export interface WordPack {
  id: string;
  name: string;
  emoji: string;
  description: string;
  games: GameId[];
  pairs: WordPair[];
}

export const WORD_PACKS: WordPack[] = [
  // ─────────────────────────────────────────────
  // BOLLYWOOD MOVIES
  // ─────────────────────────────────────────────
  {
    id: "bollywood",
    name: "Bollywood Movies",
    emoji: "🎬",
    description: "Hindi cinema 2000–2025",
    games: ["wordspy", "pictionary", "dumbcharades"],
    pairs: [
      { word1: "Lagaan", word2: "Swades" },
      { word1: "Dilwale Dulhania Le Jayenge", word2: "Mohabbatein" },
      { word1: "Kabhi Khushi Kabhie Gham", word2: "Kabhi Alvida Naa Kehna" },
      { word1: "Devdas", word2: "Umrao Jaan" },
      { word1: "Dhoom", word2: "Don" },
      { word1: "Rang De Basanti", word2: "Lakshya" },
      { word1: "Munna Bhai MBBS", word2: "Lage Raho Munna Bhai" },
      { word1: "3 Idiots", word2: "Chhichhore" },
      { word1: "Taare Zameen Par", word2: "Stanley Ka Dabba" },
      { word1: "Jab We Met", word2: "Love Aaj Kal" },
      { word1: "Chak De India", word2: "Bhaag Milkha Bhaag" },
      { word1: "Dabangg", word2: "Singham" },
      { word1: "Zindagi Na Milegi Dobara", word2: "Dil Dhadakne Do" },
      { word1: "Barfi", word2: "Rockstar" },
      { word1: "Gangs of Wasseypur", word2: "Ugly" },
      { word1: "Queen", word2: "Highway" },
      { word1: "Bajrangi Bhaijaan", word2: "Sultan" },
      { word1: "Dangal", word2: "Secret Superstar" },
      { word1: "Raazi", word2: "Uri: The Surgical Strike" },
      { word1: "Gully Boy", word2: "Udta Punjab" },
      { word1: "Andhadhun", word2: "Badla" },
      { word1: "Article 15", word2: "Thappad" },
      { word1: "Shershaah", word2: "Sam Bahadur" },
      { word1: "Pathaan", word2: "War" },
      { word1: "Brahmastra", word2: "Kalki 2898 AD" },
      { word1: "Animal", word2: "Kabir Singh" },
      { word1: "Rocky Aur Rani Ki Prem Kahani", word2: "Ae Dil Hai Mushkil" },
      { word1: "Jawan", word2: "Bade Miyan Chote Miyan" },
      { word1: "12th Fail", word2: "Super 30" },
      { word1: "Kal Ho Naa Ho", word2: "Dil To Pagal Hai" },
      { word1: "Hera Pheri", word2: "Welcome" },
      { word1: "Golmaal", word2: "Bhool Bhulaiya" },
      { word1: "Padmaavat", word2: "Bajirao Mastani" },
      { word1: "PK", word2: "Oh My God" },
      { word1: "Dil Chahta Hai", word2: "Wake Up Sid" },
      { word1: "Veer-Zaara", word2: "Fanaa" },
      { word1: "Talaash", word2: "Kahaani" },
      { word1: "Stree", word2: "Bhediya" },
      { word1: "Tumbbad", word2: "Raat Akeli Hai" },
      { word1: "Masaan", word2: "Newton" },
      { word1: "Aligarh", word2: "Omerta" },
      { word1: "Drishyam", word2: "Andhadhun" },
      { word1: "Stree 2", word2: "Munjya" },
      { word1: "Fukrey", word2: "Delhi Belly" },
      { word1: "Go Goa Gone", word2: "Happy Ending" },
      { word1: "Ludo", word2: "Ghost Stories" },
      { word1: "Crew", word2: "Merry Christmas" },
      { word1: "Farzi", word2: "Guns and Gulaabs" },
      { word1: "Jogi", word2: "Sardar Udham" },
      { word1: "Haseen Dillruba", word2: "Darlings" },
      { word1: "Laal Singh Chaddha", word2: "Atrangi Re" },
      { word1: "Mission Kashmir", word2: "Haider" },
      { word1: "Black", word2: "Saawariya" },
      { word1: "Koi Mil Gaya", word2: "Krish" },
      { word1: "Lootera", word2: "Sonchiriya" },
      { word1: "Toilet: A Love Story", word2: "Pad Man" },
      { word1: "Bala", word2: "Ujda Chaman" },
      { word1: "Sonu Ke Titu Ki Sweety", word2: "De De Pyaar De" },
      { word1: "Yeh Jawaani Hai Deewani", word2: "Tamasha" },
      { word1: "Tanu Weds Manu", word2: "Band Baaja Baaraat" },
      { word1: "Pyaar Ka Punchnama", word2: "Sonu Ke Titu Ki Sweety" },
      { word1: "Andaz Apna Apna", word2: "Jo Jeeta Wohi Sikandar" },
    ],
  },
  // ─────────────────────────────────────────────
  // TOLLYWOOD MOVIES
  // ─────────────────────────────────────────────
  {
    id: "tollywood",
    name: "Tollywood Movies",
    emoji: "🎭",
    description: "Telugu cinema 2000–2025",
    games: ["wordspy", "pictionary", "dumbcharades"],
    pairs: [
      // ── SS Rajamouli
      { word1: "Baahubali: The Beginning", word2: "Baahubali: The Conclusion" },
      { word1: "RRR", word2: "Eega" },
      { word1: "Magadheera", word2: "Chatrapathi" },
      { word1: "Simhadri", word2: "Vikramarkudu" },
      { word1: "Yamadonga", word2: "Maryada Ramanna" },

      // ── Prabhas
      { word1: "Pushpa: The Rise", word2: "Pushpa 2: The Rule" },
      { word1: "Salaar", word2: "Kalki 2898 AD" },
      { word1: "Mirchi", word2: "Rebel" },
      { word1: "Bujjigadu", word2: "Munna" },
      { word1: "Darling", word2: "Mr. Perfect" },
      { word1: "Raghavendra", word2: "Varsham" },
      { word1: "Adipurush", word2: "Saaho" },
      { word1: "Billa", word2: "Ek Niranjan" },

      // ── Mahesh Babu
      { word1: "Pokiri", word2: "Athadu" },
      { word1: "Dookudu", word2: "Businessman" },
      { word1: "Srimanthudu", word2: "Bharat Ane Nenu" },
      { word1: "Maharshi", word2: "Sarileru Neekevvaru" },
      { word1: "Okkadu", word2: "Murari" },
      { word1: "Khaleja", word2: "1: Nenokkadine" },
      { word1: "Spyder", word2: "Aagadu" },
      { word1: "Gunasekhar", word2: "Nani" },
      { word1: "Yuvaraju", word2: "Vamsi" },
      { word1: "Bobby", word2: "Sainikudu" },
      { word1: "Komaram Puli", word2: "Arjun" },
      { word1: "Prince", word2: "Superstar" },
      { word1: "Bigil", word2: "Brahmotsavam" },
      { word1: "Seethamma Vakitlo", word2: "Nenokkadine" },

      // ── Allu Arjun
      { word1: "Ala Vaikunthapurramuloo", word2: "Sarrainodu" },
      { word1: "Arya", word2: "Arya 2" },
      { word1: "Julayi", word2: "Race Gurram" },
      { word1: "DJ Duvvada Jagannadham", word2: "Naa Peru Surya" },
      { word1: "Bunny", word2: "Happy" },
      { word1: "Desamuduru", word2: "Parugu" },
      { word1: "Iddarammayilatho", word2: "Yevadu" },
      { word1: "S/O Satyamurthy", word2: "Rudhramadevi" },
      { word1: "Vedam", word2: "Badrinath" },
      { word1: "Julai", word2: "Ganga" },
      { word1: "Naa Autograph", word2: "Sukumar" },
      { word1: "Duvvada Jagannadham", word2: "Trivikram" },

      // ── Junior NTR
      { word1: "Temper", word2: "Janatha Garage" },
      { word1: "Jai Lava Kusa", word2: "Aravinda Sametha" },
      { word1: "Devara", word2: "NTR: Mahanayakudu" },
      { word1: "Brindavanam", word2: "Baadshah" },
      { word1: "Rabhasa", word2: "Nannaku Prematho" },
      { word1: "Oosaravelli", word2: "Dammu" },
      { word1: "Adhurs", word2: "Shakti" },
      { word1: "Narasimhudu", word2: "Yamadonga" },
      { word1: "Student No 1", word2: "Simhadri" },
      { word1: "Kantara", word2: "Sye" },
      { word1: "Allari Naresh", word2: "Srikanth" },
      { word1: "Rakhi", word2: "Victory" },

      // ── Ram Charan
      { word1: "Rangasthalam", word2: "Magadheera" },
      { word1: "Chirutha", word2: "Orange" },
      { word1: "Dhruva", word2: "Bruce Lee: The Ram Charan" },
      { word1: "Govindudu Andarivadele", word2: "Yevadu" },
      { word1: "Racha", word2: "Naayak" },
      { word1: "Zanjeer", word2: "Nayak" },
      { word1: "Toofan", word2: "Rachcha" },
      { word1: "Mega Power Star", word2: "Global Star" },
      { word1: "Vinaya Vidheya Rama", word2: "Acharya" },
      { word1: "Game Changer", word2: "RC 16" },

      // ── Vijay Deverakonda
      { word1: "Arjun Reddy", word2: "Dear Comrade" },
      { word1: "Taxiwaala", word2: "Nota" },
      { word1: "Geetha Govindam", word2: "Rowdy Fellow" },
      { word1: "Liger", word2: "Kushi" },
      { word1: "Family Star", word2: "Kingdom" },
      { word1: "Pellichoopulu", word2: "Ye Mantram Vesave" },
      { word1: "Meeku Matrame Cheptha", word2: "Majili" },
      { word1: "World Famous Lover", word2: "Hero" },
      { word1: "Geeta Govindam 2", word2: "Jana Gana Mana" },

      // ── Pawan Kalyan
      { word1: "Gabbar Singh", word2: "Attarintiki Daredi" },
      { word1: "Khaidi No 150", word2: "Agnyaathavaasi" },
      { word1: "Jalsa", word2: "Teen Maar" },
      { word1: "Vakeel Saab", word2: "Bheemla Nayak" },
      { word1: "Johnny", word2: "Badri" },
      { word1: "Tholi Prema", word2: "Thammudu" },
      { word1: "Suswagatham", word2: "Khushi" },
      { word1: "Bangaram", word2: "Annavaram" },
      { word1: "Sardaar Gabbar Singh", word2: "Gopala Gopala" },
      { word1: "Cameraman Ganga tho Rambabu", word2: "Panjaa" },
      { word1: "Hari Hara Veera Mallu", word2: "OG" },
      { word1: "Ustaad Bhagat Singh", word2: "They Call Him OG" },

      // ── Chiranjeevi
      { word1: "Sye Raa Narasimha Reddy", word2: "Godfather" },
      { word1: "Indra", word2: "Tagore" },
      { word1: "Stalin", word2: "Shankar Dada Zindabad" },
      { word1: "Khaidi", word2: "Rudraveena" },
      { word1: "Gang Leader", word2: "Mutha Mestri" },
      { word1: "Aakhari Poratam", word2: "Vijetha" },
      { word1: "Chantabbai", word2: "Swayam Krushi" },
      { word1: "Manchi Manushulu", word2: "Yamudiki Mogudu" },
      { word1: "Waltair Veerayya", word2: "Bholaa Shankar" },
      { word1: "Mega Star", word2: "Konidela" },

      // ── Balakrishna
      { word1: "Akhanda", word2: "Legend" },
      { word1: "Simha", word2: "Sri Rama Rajyam" },
      { word1: "Narasimha Naidu", word2: "Samarasimha Reddy" },
      { word1: "Aditya 369", word2: "Lok Parlok" },
      { word1: "Nandamuri Balakrishna", word2: "NBK" },
      { word1: "Dictator", word2: "Lion" },
      { word1: "Gautamiputra Satakarni", word2: "Paisa Vasool" },
      { word1: "Ruler", word2: "Veera Simha Reddy" },
      { word1: "Bhagavanth Kesari", word2: "NBK108" },

      // ── Venkatesh
      { word1: "Drushyam", word2: "Julayi" },
      { word1: "Masala", word2: "Shadow" },
      { word1: "Bodyguard", word2: "Namo Venkatesa" },
      { word1: "Aadavari Matalaku Ardhale Verule", word2: "Tulasi" },
      { word1: "Seethaiah", word2: "Krishnaarjuna Yuddham" },
      { word1: "F2: Fun and Frustration", word2: "F3: Fun and Frustration" },
      { word1: "Narappa", word2: "Drushyam 2" },
      { word1: "Sant Tukaram", word2: "Gajapokkiri" },

      // ── Nani
      { word1: "Jersey", word2: "Gang Leader" },
      { word1: "Majili", word2: "Middle Class Abbayi" },
      { word1: "Eega", word2: "Bhale Bhale Magadivoy" },
      { word1: "Ante Sundaraniki", word2: "Shyam Singha Roy" },
      { word1: "V", word2: "Tuck Jagadish" },
      { word1: "Hit: The First Case", word2: "Dasvi" },
      { word1: "Krishnarjuna Yuddham", word2: "Devadas" },
      { word1: "Nenu Local", word2: "Ninnu Kori" },
      { word1: "Saripodhaa Sanivaaram", word2: "Hi Nanna" },

      // ── Ravi Teja
      { word1: "Krack", word2: "Waltair Veerayya" },
      { word1: "Kick", word2: "Kick 2" },
      { word1: "Vikramarkudu", word2: "Don" },
      { word1: "Balupu", word2: "Mirapakay" },
      { word1: "Raghavendra", word2: "Bengal Tiger" },
      { word1: "Dhamaka", word2: "Ramarao On Duty" },
      { word1: "Tiger Nageswara Rao", word2: "Eagle" },
      { word1: "Mass", word2: "Neninthe" },

      // ── Kalyan Ram
      { word1: "Bimbisara", word2: "Dacoit" },
      { word1: "Om", word2: "Athanokkade" },
      { word1: "Pataas", word2: "Panjaa" },

      // ── Sharwanand
      { word1: "Malli Malli Idi Rani Roju", word2: "Padi Padi Leche Manasu" },
      { word1: "Mahanubhavudu", word2: "Ranarangam" },
      { word1: "Oke Oka Jeevitham", word2: "Sreekaram" },

      // ── Adivi Sesh
      { word1: "HanuMan", word2: "Goodachari" },
      { word1: "Saindhav", word2: "Major" },
      { word1: "Itlu Maredumilli Prajaneekam", word2: "Evaru" },

      // ── Romantic / Drama
      { word1: "Bommarillu", word2: "Happy Days" },
      { word1: "Fidaa", word2: "Ye Maaya Chesave" },
      { word1: "Pelli Choopulu", word2: "Chal Mohan Ranga" },
      { word1: "Bheeshma", word2: "Vunnadhi Okate Zindagi" },
      { word1: "Uppena", word2: "Tuck Jagadish" },
      { word1: "Nuvvostanante Nenoddantana", word2: "Manmadhudu" },
      { word1: "Tholi Prema", word2: "Premikudu" },
      { word1: "Nuvvu Nenu", word2: "Oka Laila Kosam" },
      { word1: "Kotha Bangaru Lokam", word2: "Ishq" },
      { word1: "Manam", word2: "Oohalu Gusagusalade" },
    ],
  },
  // ─────────────────────────────────────────────
  // CRICKET
  // ─────────────────────────────────────────────
  {
    id: "cricket",
    name: "Cricket",
    emoji: "🏏",
    description: "India's religion",
    games: ["wordspy", "pictionary", "dumbcharades"],
    pairs: [
      { word1: "Virat Kohli", word2: "Rohit Sharma" },
      { word1: "MS Dhoni", word2: "Sourav Ganguly" },
      { word1: "Sachin Tendulkar", word2: "Brian Lara" },
      { word1: "Jasprit Bumrah", word2: "Mohammed Shami" },
      { word1: "Suresh Raina", word2: "Yuvraj Singh" },
      { word1: "Anil Kumble", word2: "Ravichandran Ashwin" },
      { word1: "Ravindra Jadeja", word2: "Kuldeep Yadav" },
      { word1: "Shikhar Dhawan", word2: "KL Rahul" },
      { word1: "Hardik Pandya", word2: "Rishabh Pant" },
      { word1: "Sunil Gavaskar", word2: "Kapil Dev" },
      { word1: "Zaheer Khan", word2: "Ishant Sharma" },
      { word1: "VVS Laxman", word2: "Rahul Dravid" },
      { word1: "Harbhajan Singh", word2: "Pragyan Ojha" },
      { word1: "Dinesh Karthik", word2: "Sanju Samson" },
      { word1: "Shreyas Iyer", word2: "Shubman Gill" },
      { word1: "Yashasvi Jaiswal", word2: "Ruturaj Gaikwad" },
      { word1: "Tilak Varma", word2: "Rinku Singh" },
      { word1: "Virender Sehwag", word2: "Gautam Gambhir" },
      { word1: "Mohammad Azharuddin", word2: "Ajay Jadeja" },
      { word1: "Irfan Pathan", word2: "Yusuf Pathan" },
      { word1: "Ajinkya Rahane", word2: "Cheteshwar Pujara" },
      { word1: "Umesh Yadav", word2: "Mohammed Siraj" },
      { word1: "Deepak Chahar", word2: "Arshdeep Singh" },
      { word1: "Axar Patel", word2: "Washington Sundar" },
      { word1: "Shardul Thakur", word2: "Bhuvneshwar Kumar" },
      { word1: "Ishan Kishan", word2: "Prithvi Shaw" },
      { word1: "Abhishek Sharma", word2: "Nitish Kumar Reddy" },
      { word1: "Munaf Patel", word2: "S Sreesanth" },
      { word1: "RP Singh", word2: "Ashish Nehra" },
      { word1: "IPL", word2: "T20 World Cup" },
      { word1: "Test Match", word2: "One Day International" },
      { word1: "Mumbai Indians", word2: "Chennai Super Kings" },
      { word1: "Eden Gardens", word2: "Wankhede Stadium" },
      { word1: "Yorker", word2: "Bouncer" },
      { word1: "Six", word2: "Four" },
      { word1: "Leg Before Wicket", word2: "Bowled Out" },
      { word1: "Spin Bowling", word2: "Fast Bowling" },
      { word1: "Cover Drive", word2: "Square Cut" },
      { word1: "Decision Review System", word2: "Hawkeye" },
      { word1: "Powerplay", word2: "Death Overs" },
      { word1: "Slip Fielding", word2: "Gully Fielding" },
      { word1: "Swing Bowling", word2: "Seam Bowling" },
      { word1: "Cricket World Cup", word2: "Asia Cup" },
      { word1: "Royal Challengers Bangalore", word2: "Kolkata Knight Riders" },
      { word1: "Delhi Capitals", word2: "Punjab Kings" },
      { word1: "Sunrisers Hyderabad", word2: "Rajasthan Royals" },
      { word1: "Lucknow Super Giants", word2: "Gujarat Titans" },
      { word1: "Chinnaswamy Stadium", word2: "Narendra Modi Stadium" },
      { word1: "Chepauk Stadium", word2: "Feroz Shah Kotla" },
      { word1: "Super Over", word2: "Bowl-Out" },
      { word1: "Duck", word2: "Golden Duck" },
      { word1: "Century", word2: "Half Century" },
      { word1: "Hat Trick", word2: "Five Wicket Haul" },
      { word1: "Maiden Over", word2: "Dot Ball" },
      { word1: "Stumped", word2: "Caught Out" },
      { word1: "Test Championship", word2: "Champions Trophy" },
      { word1: "Ashes Series", word2: "Border-Gavaskar Trophy" },
      { word1: "No Ball", word2: "Wide Ball" },
      { word1: "Run Out", word2: "Hit Wicket" },
    ],
  },
  // ─────────────────────────────────────────────
  // BOLLYWOOD ACTORS
  // ─────────────────────────────────────────────
  {
    id: "actors",
    name: "Bollywood Actors",
    emoji: "🌟",
    description: "Stars of Hindi cinema",
    games: ["wordspy", "pictionary", "dumbcharades"],
    pairs: [
      { word1: "Shah Rukh Khan", word2: "Salman Khan" },
      { word1: "Deepika Padukone", word2: "Priyanka Chopra" },
      { word1: "Ranveer Singh", word2: "Ranbir Kapoor" },
      { word1: "Alia Bhatt", word2: "Katrina Kaif" },
      { word1: "Amitabh Bachchan", word2: "Dharmendra" },
      { word1: "Ayushmann Khurrana", word2: "Rajkummar Rao" },
      { word1: "Taapsee Pannu", word2: "Bhumi Pednekar" },
      { word1: "Vijay Deverakonda", word2: "Kartik Aaryan" },
      { word1: "Kangana Ranaut", word2: "Vidya Balan" },
      { word1: "Nawazuddin Siddiqui", word2: "Manoj Bajpayee" },
      { word1: "Hrithik Roshan", word2: "Tiger Shroff" },
      { word1: "Akshay Kumar", word2: "Ajay Devgn" },
      { word1: "Varun Dhawan", word2: "Siddhant Chaturvedi" },
      { word1: "Janhvi Kapoor", word2: "Sara Ali Khan" },
      { word1: "Ananya Panday", word2: "Rakul Preet Singh" },
      { word1: "Sidharth Malhotra", word2: "Arjun Kapoor" },
      { word1: "Emraan Hashmi", word2: "John Abraham" },
      { word1: "Kareena Kapoor", word2: "Karisma Kapoor" },
      { word1: "Aishwarya Rai Bachchan", word2: "Madhuri Dixit" },
      { word1: "Jacqueline Fernandez", word2: "Disha Patani" },
      { word1: "Bobby Deol", word2: "Sunny Deol" },
      { word1: "Rishi Kapoor", word2: "Jeetendra" },
      { word1: "Farhan Akhtar", word2: "Abhay Deol" },
      { word1: "Irrfan Khan", word2: "Naseeruddin Shah" },
      { word1: "Pankaj Tripathi", word2: "Rajpal Yadav" },
      { word1: "Boman Irani", word2: "Paresh Rawal" },
      { word1: "Anupam Kher", word2: "Om Puri" },
      { word1: "Dimple Kapadia", word2: "Hema Malini" },
      { word1: "Rekha", word2: "Sridevi" },
      { word1: "Juhi Chawla", word2: "Revathi" },
      { word1: "Konkona Sen Sharma", word2: "Kalki Koechlin" },
      { word1: "Swara Bhasker", word2: "Radhika Apte" },
      { word1: "Shefali Shah", word2: "Tillotama Shome" },
      { word1: "Nora Fatehi", word2: "Malaika Arora" },
      { word1: "Divyenndu", word2: "Ali Fazal" },
      { word1: "Saif Ali Khan", word2: "Shahid Kapoor" },
      { word1: "Sanjay Dutt", word2: "Jackie Shroff" },
      { word1: "Suniel Shetty", word2: "Mithun Chakraborty" },
      { word1: "Govinda", word2: "Sanjay Mishra" },
      { word1: "Kriti Sanon", word2: "Shraddha Kapoor" },
      { word1: "Sonakshi Sinha", word2: "Huma Qureshi" },
      { word1: "Richa Chadha", word2: "Zeenat Aman" },
      { word1: "Aditi Rao Hydari", word2: "Tara Sutaria" },
      { word1: "Sanya Malhotra", word2: "Fatima Sana Shaikh" },
      { word1: "Vicky Kaushal", word2: "Aditya Roy Kapur" },
      { word1: "Randeep Hooda", word2: "Arjun Rampal" },
    ],
  },
  // ─────────────────────────────────────────────
  // INDIAN MUSIC ARTISTS
  // ─────────────────────────────────────────────
  {
    id: "indian-music",
    name: "Indian Music Artists",
    emoji: "🎵",
    description: "Singers, composers and legends",
    games: ["wordspy", "dumbcharades"],
    pairs: [
      { word1: "Arijit Singh", word2: "Atif Aslam" },
      { word1: "AR Rahman", word2: "Shankar Ehsaan Loy" },
      { word1: "Shreya Ghoshal", word2: "Sunidhi Chauhan" },
      { word1: "Sonu Nigam", word2: "Udit Narayan" },
      { word1: "Kumar Sanu", word2: "Mohammed Aziz" },
      { word1: "Lata Mangeshkar", word2: "Asha Bhosle" },
      { word1: "Kishore Kumar", word2: "Mohammed Rafi" },
      { word1: "Nucleya", word2: "Ritviz" },
      { word1: "Divine", word2: "Naezy" },
      { word1: "Prateek Kuhad", word2: "Ankur Tewari" },
      { word1: "The Local Train", word2: "Indian Ocean" },
      { word1: "Euphoria", word2: "Agnee" },
      { word1: "Papon", word2: "Kailash Kher" },
      { word1: "Hariharan", word2: "Shankar Mahadevan" },
      { word1: "Vishal Bhardwaj", word2: "Pritam" },
      { word1: "Anu Malik", word2: "Himesh Reshammiya" },
      { word1: "Daler Mehndi", word2: "Gurdas Maan" },
      { word1: "Hans Raj Hans", word2: "Malkit Singh" },
      { word1: "Usha Uthup", word2: "Kavita Krishnamurthy" },
      { word1: "SP Balasubrahmanyam", word2: "KJ Yesudas" },
      { word1: "Ilayaraja", word2: "AR Rahman" },
      { word1: "Yuvan Shankar Raja", word2: "D Imman" },
      { word1: "Anirudh Ravichander", word2: "Thaman S" },
      { word1: "Vishal-Shekhar", word2: "Meet Bros" },
      { word1: "Badshah", word2: "Yo Yo Honey Singh" },
      { word1: "AP Dhillon", word2: "Shubh" },
      { word1: "Sidhu Moosewala", word2: "Amrit Maan" },
      { word1: "Guru Randhawa", word2: "Hardy Sandhu" },
      { word1: "Neha Kakkar", word2: "Tulsi Kumar" },
      { word1: "Armaan Malik", word2: "Darshan Raval" },
      { word1: "Jubin Nautiyal", word2: "B Praak" },
      { word1: "Stebin Ben", word2: "Vishal Mishra" },
      { word1: "Alka Yagnik", word2: "Kavita Subramaniam" },
      { word1: "Rahat Fateh Ali Khan", word2: "Nusrat Fateh Ali Khan" },
      { word1: "Zakir Hussain", word2: "Bismillah Khan" },
      { word1: "Pandit Bhimsen Joshi", word2: "MS Subbulakshmi" },
      { word1: "Kanika Kapoor", word2: "Shalmali Kholgade" },
      { word1: "Monali Thakur", word2: "Jonita Gandhi" },
      { word1: "KK", word2: "Shaan" },
      { word1: "Sukhwinder Singh", word2: "Mika Singh" },
      { word1: "Benny Dayal", word2: "Mohit Chauhan" },
      { word1: "Amit Trivedi", word2: "Clinton Cerejo" },
      { word1: "Sachin-Jigar", word2: "Salim-Sulaiman" },
    ],
  },
  // ─────────────────────────────────────────────
  // TOLLYWOOD SONGS
  // ─────────────────────────────────────────────
  {
    id: "tollywood-songs",
    name: "Tollywood Songs",
    emoji: "🎸",
    description: "Iconic Telugu and Tamil songs",
    games: ["wordspy", "dumbcharades"],
    pairs: [
      { word1: "Srivalli", word2: "Oo Antava" },
      { word1: "Naatu Naatu", word2: "Komuram Bheemudo" },
      { word1: "Pushpa Pushpa", word2: "Kissik" },
      { word1: "Butta Bomma", word2: "Samajavaragamana" },
      { word1: "Ramuloo Ramulaa", word2: "Butta Bomma" },
      { word1: "Vaathi Coming", word2: "Arabic Kuthu" },
      { word1: "Rowdy Baby", word2: "Sodakku" },
      { word1: "Roja Roja", word2: "Dil Se Re" },
      { word1: "Chinna Chinna Aasai", word2: "Mustafa Mustafa" },
      { word1: "Nenjukkul Peidhidum", word2: "Vennilave Vennilave" },
      { word1: "Kannazhaga", word2: "Oru Deivam Thantha Poove" },
      { word1: "Kadhal Rojave", word2: "Ennavale Adi Ennavale" },
      { word1: "Kutti Story", word2: "Vaathi Coming" },
      { word1: "Kaavaalaa", word2: "Hukum" },
      { word1: "Jigelu Rani", word2: "Rangamma Mangamma" },
      { word1: "Saami Saami", word2: "Oo Solriya" },
      { word1: "Seeti Maar", word2: "Butta Bomma" },
      { word1: "Chuttamalle", word2: "Kissik" },
      { word1: "Daakko Daakko Meka", word2: "Srivalli" },
      { word1: "Oruvan Oruvan Mudhalali", word2: "Pokiri Title" },
      { word1: "Thillana Thillana", word2: "Urvasi Urvasi" },
      { word1: "Munbe Vaa", word2: "Yaar Indha Saalai" },
      { word1: "Unnai Kaanadhu Naan", word2: "Ennodu Nee Irundhaal" },
      { word1: "Aye Sinamika", word2: "Oh Manapenne" },
      { word1: "Petta Paraak", word2: "Marana Mass" },
      { word1: "Aaluma Doluma", word2: "Po Po Song" },
      { word1: "Dheem Tana", word2: "Pakka Local" },
      { word1: "Geetha Govindam Title Song", word2: "Ye Sundaraniki" },
      { word1: "Inkem Inkem", word2: "Manasuna" },
      { word1: "Nuvvostanante Nenoddantana", word2: "Manmadhudu Title" },
      { word1: "Jalsa Title", word2: "Ready Title Song" },
      { word1: "Gabbar Singh Theme", word2: "Dookudu Title" },
      { word1: "Race Gurram Theme", word2: "Julayi Title" },
      { word1: "Bomma Blockbuster", word2: "Akhanda Title" },
      { word1: "Seethamma Vakitlo", word2: "Adiga Adiga" },
      { word1: "Kotha Janta", word2: "Attarintiki Daredi Title" },
      { word1: "Happy Days Title", word2: "Magadheera Theme" },
      { word1: "Pokiri Item Song", word2: "Athadu Title" },
      { word1: "Nee Jathaga Nenundali", word2: "Oka Laila Kosam" },
      { word1: "Yem Maya Chesave", word2: "Oh Baby Title" },
      { word1: "Vachinde", word2: "Inkem Inkem Inkem Kaavaale" },
      { word1: "Sarainodu Title", word2: "Blockbuster Song" },
      { word1: "Yevadu Title", word2: "Iddarammayilatho Title" },
      { word1: "Mirchi Title Song", word2: "Legend Title Song" },
      { word1: "Dil Raju Title", word2: "Bommarillu Title" },
    ],
  },
  // ─────────────────────────────────────────────
  // BOLLYWOOD SONGS
  // ─────────────────────────────────────────────
  {
    id: "bollywood-songs",
    name: "Bollywood Songs",
    emoji: "🎶",
    description: "Iconic songs from Hindi films",
    games: ["wordspy", "dumbcharades"],
    pairs: [
      { word1: "Tum Hi Ho", word2: "Teri Mitti" },
      { word1: "Chaiyya Chaiyya", word2: "Jai Ho" },
      { word1: "Ae Watan", word2: "Rang De Basanti Title" },
      { word1: "Galliyan", word2: "Teri Galiyan" },
      { word1: "Kesariya", word2: "Raataan Lambiyan" },
      { word1: "Apna Time Aayega", word2: "Mere Gully Mein" },
      { word1: "Besharam Rang", word2: "Jhoome Jo Pathaan" },
      { word1: "Kala Chashma", word2: "Morni Banke" },
      { word1: "Badtameez Dil", word2: "Ghungroo" },
      { word1: "Dilbar", word2: "Kamariya" },
      { word1: "Tip Tip Barsa Paani", word2: "Chikni Chameli" },
      { word1: "Kajra Re", word2: "Bole Chudiyan" },
      { word1: "Lag Ja Gale", word2: "Tere Bina" },
      { word1: "Kal Ho Naa Ho Title", word2: "Kabhi Alvida Naa Kehna Title" },
      { word1: "Pehla Nasha", word2: "Pehli Baar Mohabbat" },
      { word1: "Kuch Kuch Hota Hai Title", word2: "Tujhe Yaad Na Meri Aaye" },
      { word1: "Aashiqui 2 Theme", word2: "Sun Raha Hai Na Tu" },
      { word1: "Channa Mereya", word2: "Bulleya" },
      { word1: "Ae Dil Hai Mushkil Title", word2: "Hawayein" },
      { word1: "Tujh Mein Rab Dikhta Hai", word2: "Tere Haath Mein" },
      { word1: "Jai Jai Shiv Shankar", word2: "Bam Bhole" },
      { word1: "Dama Dam Mast Qalandar", word2: "Heer" },
      { word1: "Mere Sapno Ki Rani", word2: "Roop Tera Mastana" },
      { word1: "Aaja Nachle", word2: "Dola Re Dola" },
      { word1: "Tere Naam Title", word2: "Main Agar Kahoon" },
      { word1: "Soch Na Sake", word2: "Ik Vaari Aa" },
      { word1: "Aankhein Khuli Ho Ya Band", word2: "Dekha Jo Tujhe Yaar" },
      { word1: "Dard-E-Disco", word2: "Beedi Jalaile" },
      { word1: "Senorita", word2: "Hum Tum Title" },
      { word1: "Dus Bahane", word2: "Abhi Toh Party Shuru Hui Hai" },
      { word1: "Deva Deva", word2: "Brahmastra Theme" },
      { word1: "Arjan Vailly", word2: "Ranbir Animal Theme" },
      { word1: "Malang Title", word2: "Chal Ghar Chalen" },
      { word1: "Tera Yaar Hoon Main", word2: "Dost Dost Na Raha" },
      { word1: "Aur Ho", word2: "Safar" },
      { word1: "Humdard", word2: "Muskurane" },
      { word1: "Suno Na Sangemarmar", word2: "Main Rang Sharbaton Ka" },
      { word1: "Phir Le Aya Dil", word2: "Aayat" },
      { word1: "Agar Tum Saath Ho", word2: "Channa Mereya" },
      { word1: "Enna Sona", word2: "Gerua" },
      { word1: "Khairiyat", word2: "Teri Bhi Khoob Hai" },
      { word1: "Bekhayali", word2: "Tera Ban Jaunga" },
      { word1: "Ve Maahi", word2: "Ye Tune Kya Kiya" },
      { word1: "Ijazat", word2: "Saiyaara" },
      { word1: "Tanha Tanha", word2: "Pehla Pehla Pyaar" },
    ],
  },
  // ─────────────────────────────────────────────
  // INDIAN POLITICS
  // ─────────────────────────────────────────────
  {
    id: "indian-politics",
    name: "Indian Politics",
    emoji: "🏛️",
    description: "Leaders who shaped India",
    games: ["wordspy", "pictionary", "dumbcharades"],
    pairs: [
      { word1: "Narendra Modi", word2: "Amit Shah" },
      { word1: "Rahul Gandhi", word2: "Priyanka Gandhi" },
      { word1: "Arvind Kejriwal", word2: "Manish Sisodia" },
      { word1: "Mamata Banerjee", word2: "Abhishek Banerjee" },
      { word1: "Yogi Adityanath", word2: "Shivraj Singh Chouhan" },
      { word1: "K Chandrashekhar Rao", word2: "Revanth Reddy" },
      { word1: "Uddhav Thackeray", word2: "Eknath Shinde" },
      { word1: "Sharad Pawar", word2: "Ajit Pawar" },
      { word1: "Nitish Kumar", word2: "Tejashwi Yadav" },
      { word1: "Lalu Prasad Yadav", word2: "Ram Vilas Paswan" },
      { word1: "Naveen Patnaik", word2: "Mohan Majhi" },
      { word1: "MK Stalin", word2: "Edappadi Palaniswami" },
      { word1: "Jayalalithaa", word2: "Karunanidhi" },
      { word1: "Siddaramaiah", word2: "HD Kumaraswamy" },
      { word1: "Pinarayi Vijayan", word2: "Oommen Chandy" },
      { word1: "Jawaharlal Nehru", word2: "Sardar Vallabhbhai Patel" },
      { word1: "Indira Gandhi", word2: "Rajiv Gandhi" },
      { word1: "Atal Bihari Vajpayee", word2: "LK Advani" },
      { word1: "Manmohan Singh", word2: "PV Narasimha Rao" },
      { word1: "APJ Abdul Kalam", word2: "KR Narayanan" },
      { word1: "Pranab Mukherjee", word2: "Pratibha Patil" },
      { word1: "BR Ambedkar", word2: "Ram Manohar Lohia" },
      { word1: "Subhas Chandra Bose", word2: "Bhagat Singh" },
      { word1: "Bal Gangadhar Tilak", word2: "Gopal Krishna Gokhale" },
      { word1: "Chandrashekhar", word2: "VP Singh" },
      { word1: "IK Gujral", word2: "HD Deve Gowda" },
      { word1: "Sonia Gandhi", word2: "Mallikarjun Kharge" },
      { word1: "Smriti Irani", word2: "Nirmala Sitharaman" },
      { word1: "S Jaishankar", word2: "Rajnath Singh" },
      { word1: "Hemant Soren", word2: "Champai Soren" },
      { word1: "Omar Abdullah", word2: "Farooq Abdullah" },
      { word1: "N Chandrababu Naidu", word2: "YS Jaganmohan Reddy" },
      { word1: "Mehbooba Mufti", word2: "Ghulam Nabi Azad" },
    ],
  },
  // ─────────────────────────────────────────────
  // DESI STREET FOOD
  // ─────────────────────────────────────────────
  {
    id: "street-food",
    name: "Desi Street Food",
    emoji: "🥘",
    description: "India's best street eats",
    games: ["wordspy", "pictionary"],
    pairs: [
      { word1: "Pani Puri", word2: "Sev Puri" },
      { word1: "Vada Pav", word2: "Dabeli" },
      { word1: "Pav Bhaji", word2: "Misal Pav" },
      { word1: "Bhel Puri", word2: "Aloo Chaat" },
      { word1: "Kathi Roll", word2: "Egg Roll" },
      { word1: "Papdi Chaat", word2: "Dahi Papdi Chaat" },
      { word1: "Litti Chokha", word2: "Bati Churma" },
      { word1: "Momos", word2: "Dim Sum" },
      { word1: "Dahi Bhalle", word2: "Dahi Vada" },
      { word1: "Tikki Chaat", word2: "Rajma Chaat" },
      { word1: "Falooda", word2: "Rose Milk" },
      { word1: "Gol Gappa", word2: "Batata Puri" },
      { word1: "Ragda Pattice", word2: "Sev Batata Puri" },
      { word1: "Jhal Muri", word2: "Churmur" },
      { word1: "Onion Pakora", word2: "Chilli Pakora" },
      { word1: "Corn Pakora", word2: "Bread Pakora" },
      { word1: "Egg Bhurji", word2: "Paneer Bhurji" },
      { word1: "Tawa Pulao", word2: "Schezwan Fried Rice" },
      { word1: "Keema Pav", word2: "Chicken Frankie" },
      { word1: "Bun Maska", word2: "Irani Chai" },
      { word1: "Sugarcane Juice", word2: "Nimbu Pani" },
      { word1: "Kulfi Faluda", word2: "Rabri Faluda" },
      { word1: "Stuffed Chilli Bajji", word2: "Aloo Bajji" },
      { word1: "Punugulu", word2: "Mullangi Bajji" },
      { word1: "Boiled Chickpeas", word2: "Masala Peanuts" },
      { word1: "Tandoori Chai", word2: "Kulhad Coffee" },
      { word1: "Kanda Poha", word2: "Batata Poha" },
      { word1: "Sabudana Vada", word2: "Sabudana Khichdi" },
      { word1: "Momo Chilli", word2: "Momo Soup" },
      { word1: "Ram Ladoo", word2: "Chhole Kulche" },
      { word1: "Butter Corn", word2: "Masala Corn" },
      { word1: "Samosa", word2: "Kachori" },
      { word1: "Aloo Tikki", word2: "Paneer Tikki" },
      { word1: "Roasted Peanuts", word2: "Boiled Corn" },
      { word1: "Coconut Water", word2: "Cane Juice" },
      { word1: "Mirchi Bajji", word2: "Aloo Tikki Chaat" },
      { word1: "Frankie", word2: "Kothu Parotta" },
      { word1: "Poha Jalebi", word2: "Upma Vada" },
      { word1: "Sevpuri", word2: "Ragda Puri" },
      { word1: "Lassi", word2: "Chaas" },
      { word1: "Chole Bhature", word2: "Puri Sabzi" },
      { word1: "Gulab Jamun", word2: "Jalebi" },
      { word1: "Paneer Roll", word2: "Aloo Roll" },
      { word1: "Corn Chaat", word2: "Papaya Chaat" },
    ],
  },
  // ─────────────────────────────────────────────
  // SOUTH INDIAN FOOD (FAMOUS WORLDWIDE)
  // ─────────────────────────────────────────────
  {
    id: "south-indian-usa",
    name: "South Indian Food",
    emoji: "🍛",
    description: "South Indian dishes loved worldwide",
    games: ["wordspy", "pictionary"],
    pairs: [
      { word1: "Masala Dosa", word2: "Plain Dosa" },
      { word1: "Rava Dosa", word2: "Paper Dosa" },
      { word1: "Set Dosa", word2: "Uttapam" },
      { word1: "Idli", word2: "Vada" },
      { word1: "Sambar", word2: "Rasam" },
      { word1: "Coconut Chutney", word2: "Tomato Chutney" },
      { word1: "Chicken Biryani", word2: "Hyderabadi Biryani" },
      { word1: "Chettinad Biryani", word2: "Malabar Biryani" },
      { word1: "Chicken Chettinad", word2: "Andhra Chilli Chicken" },
      { word1: "Medu Vada", word2: "Masala Vada" },
      { word1: "Filter Coffee", word2: "Madras Coffee" },
      { word1: "Pongal", word2: "Upma" },
      { word1: "Bisi Bele Bath", word2: "Lemon Rice" },
      { word1: "Tamarind Rice", word2: "Coconut Rice" },
      { word1: "Curd Rice", word2: "Tomato Rice" },
      { word1: "Paneer Dosa", word2: "Egg Dosa" },
      { word1: "Appam", word2: "String Hoppers" },
      { word1: "Payasam", word2: "Kheer" },
      { word1: "Kerala Fish Curry", word2: "Meen Kuzhambu" },
      { word1: "Fish Fry", word2: "Prawn Fry" },
      { word1: "Chicken 65", word2: "Gobi 65" },
      { word1: "Paneer 65", word2: "Mushroom 65" },
      { word1: "Pesarattu", word2: "Kanda Pesarattu" },
      { word1: "Avial", word2: "Thoran" },
      { word1: "Kerala Prawn Curry", word2: "Fish Molee" },
      { word1: "Kerala Sadya", word2: "Banana Leaf Feast" },
      { word1: "Puttu", word2: "Idiyappam" },
      { word1: "Parotta", word2: "Kothu Parotta" },
      { word1: "Banana Leaf Rice", word2: "Thali Meal" },
      { word1: "Sambar Rice", word2: "Rasam Rice" },
      { word1: "Sundal", word2: "Chickpea Salad" },
      { word1: "Mysore Pak", word2: "Tirunelveli Halwa" },
      { word1: "Gulab Jamun", word2: "Rasgulla" },
      { word1: "Mango Lassi", word2: "Buttermilk" },
      { word1: "Tender Coconut Water", word2: "Sugarcane Juice" },
      { word1: "Aloo Kurma", word2: "Mixed Vegetable Kurma" },
      { word1: "Ghee Rice", word2: "Jeera Rice" },
      { word1: "Murukku", word2: "Chakli" },
      { word1: "Ribbon Pakoda", word2: "Diamond Cuts" },
      { word1: "Egg Curry", word2: "Paneer Curry" },
      { word1: "Cauliflower Stir Fry", word2: "Brinjal Curry" },
      { word1: "Cabbage Poriyal", word2: "Beans Poriyal" },
      { word1: "Prawn Masala", word2: "Crab Curry" },
      { word1: "Mutton Biryani", word2: "Fish Biryani" },
      { word1: "Chettinad Pepper Chicken", word2: "Andhra Spicy Chicken" },
    ],
  },
  // ─────────────────────────────────────────────
  // ANIMALS
  // ─────────────────────────────────────────────
  {
    id: "animals",
    name: "Animals",
    emoji: "🐾",
    description: "From jungles to oceans",
    games: ["wordspy", "pictionary", "dumbcharades"],
    pairs: [
      { word1: "Peacock", word2: "Flamingo" },
      { word1: "Sloth", word2: "Platypus" },
      { word1: "Chameleon", word2: "Gecko" },
      { word1: "Mongoose", word2: "Meerkat" },
      { word1: "Walrus", word2: "Narwhal" },
      { word1: "Porcupine", word2: "Pangolin" },
      { word1: "Orangutan", word2: "Chimpanzee" },
      { word1: "Armadillo", word2: "Anteater" },
      { word1: "Pelican", word2: "Toucan" },
      { word1: "Hyena", word2: "Warthog" },
      { word1: "Komodo Dragon", word2: "Iguana" },
      { word1: "Hammerhead Shark", word2: "Stingray" },
      { word1: "Octopus", word2: "Jellyfish" },
      { word1: "Penguin", word2: "Polar Bear" },
      { word1: "Camel", word2: "Llama" },
      { word1: "Elephant", word2: "Rhinoceros" },
      { word1: "Gorilla", word2: "Baboon" },
      { word1: "Snow Leopard", word2: "Cheetah" },
      { word1: "Crocodile", word2: "Alligator" },
      { word1: "Hummingbird", word2: "Woodpecker" },
      { word1: "Cobra", word2: "Python" },
      { word1: "Firefly", word2: "Praying Mantis" },
      { word1: "Stork", word2: "Crane" },
      { word1: "Bison", word2: "Yak" },
      { word1: "Dolphin", word2: "Orca" },
    ],
  },
  // ─────────────────────────────────────────────
  // PROFESSIONS
  // ─────────────────────────────────────────────
  {
    id: "professions",
    name: "Professions",
    emoji: "💼",
    description: "Jobs that are fun to act out",
    games: ["pictionary", "dumbcharades"],
    pairs: [
      { word1: "Magician", word2: "Juggler" },
      { word1: "Surgeon", word2: "Dentist" },
      { word1: "Astronaut", word2: "Pilot" },
      { word1: "Lifeguard", word2: "Firefighter" },
      { word1: "Puppeteer", word2: "Ventriloquist" },
      { word1: "Referee", word2: "Umpire" },
      { word1: "Pickpocket", word2: "Bodyguard" },
      { word1: "Tightrope Walker", word2: "Trapeze Artist" },
      { word1: "Mime", word2: "Clown" },
      { word1: "Conductor", word2: "DJ" },
      { word1: "Archaeologist", word2: "Geologist" },
      { word1: "Sommelier", word2: "Chef" },
      { word1: "Paparazzi", word2: "Photographer" },
      { word1: "Meteorologist", word2: "News Anchor" },
      { word1: "Fisherman", word2: "Lumberjack" },
      { word1: "Jockey", word2: "Bullfighter" },
      { word1: "Bouncer", word2: "Locksmith" },
      { word1: "Florist", word2: "Tailor" },
      { word1: "Monk", word2: "Nun" },
      { word1: "Spy", word2: "Detective" },
    ],
  },
  // ─────────────────────────────────────────────
  // ENGLISH TV SHOWS & WEB SERIES
  // ─────────────────────────────────────────────
  {
    id: "english-shows",
    name: "English TV Shows",
    emoji: "📺",
    description: "Binge-worthy international series",
    games: ["wordspy", "dumbcharades"],
    pairs: [
      { word1: "Breaking Bad", word2: "Better Call Saul" },
      { word1: "Game of Thrones", word2: "House of the Dragon" },
      { word1: "Stranger Things", word2: "Dark" },
      { word1: "The Office", word2: "Parks and Recreation" },
      { word1: "Friends", word2: "How I Met Your Mother" },
      { word1: "Sherlock", word2: "Peaky Blinders" },
      { word1: "The Crown", word2: "Downton Abbey" },
      { word1: "Black Mirror", word2: "Westworld" },
      { word1: "Money Heist", word2: "Squid Game" },
      { word1: "The Boys", word2: "Invincible" },
      { word1: "Succession", word2: "Billions" },
      { word1: "Chernobyl", word2: "Band of Brothers" },
      { word1: "The Witcher", word2: "Vikings" },
      { word1: "Dexter", word2: "Hannibal" },
      { word1: "Ted Lasso", word2: "Schitt's Creek" },
      { word1: "Fleabag", word2: "Killing Eve" },
      { word1: "Euphoria", word2: "Skins" },
      { word1: "Narcos", word2: "Ozark" },
      { word1: "The Last of Us", word2: "The Walking Dead" },
      { word1: "White Lotus", word2: "Big Little Lies" },
      { word1: "Lost", word2: "Prison Break" },
      { word1: "24", word2: "Homeland" },
      { word1: "Suits", word2: "Billions" },
      { word1: "House MD", word2: "Grey's Anatomy" },
      { word1: "The Good Place", word2: "Brooklyn Nine-Nine" },
      { word1: "It's Always Sunny in Philadelphia", word2: "Arrested Development" },
      { word1: "Seinfeld", word2: "Curb Your Enthusiasm" },
      { word1: "The Wire", word2: "The Sopranos" },
      { word1: "True Detective", word2: "Mindhunter" },
      { word1: "Severance", word2: "Halt and Catch Fire" },
      { word1: "Andor", word2: "The Mandalorian" },
      { word1: "Loki", word2: "WandaVision" },
      { word1: "The Bear", word2: "Beef" },
      { word1: "Abbott Elementary", word2: "Ghosts" },
      { word1: "Only Murders in the Building", word2: "Monk" },
      { word1: "Slow Horses", word2: "The Night Manager" },
      { word1: "Shogun", word2: "The Tudors" },
      { word1: "Rome", word2: "Spartacus" },
      { word1: "Boardwalk Empire", word2: "Deadwood" },
      { word1: "Mad Men", word2: "Halt and Catch Fire" },
      { word1: "Fargo", word2: "True Blood" },
      { word1: "American Horror Story", word2: "The Haunting of Hill House" },
      { word1: "The X-Files", word2: "Twin Peaks" },
      { word1: "Buffy the Vampire Slayer", word2: "Supernatural" },
      { word1: "Battlestar Galactica", word2: "Firefly" },
      { word1: "Stargate", word2: "Star Trek" },
      { word1: "Doctor Who", word2: "Merlin" },
      { word1: "Downton Abbey", word2: "The Great British Bake Off" },
      { word1: "Derry Girls", word2: "Sex Education" },
      { word1: "Normal People", word2: "Sally Rooney" },
      { word1: "Saltburn", word2: "The Favourite" },
      { word1: "Baby Reindeer", word2: "Adolescence" },
      { word1: "The Gentlemen", word2: "Bodyguard" },
      { word1: "Top Boy", word2: "Gangs of London" },
      { word1: "Industry", word2: "Succession" },
      { word1: "Yellowstone", word2: "1883" },
      { word1: "Reacher", word2: "Jack Ryan" },
      { word1: "The Terminal List", word2: "Tulsa King" },
      { word1: "Cobra Kai", word2: "Karate Kid" },
      { word1: "Squid Game", word2: "All of Us Are Dead" },
      { word1: "Kingdom", word2: "Crash Landing on You" },
      { word1: "Emily in Paris", word2: "Lupin" },
      { word1: "Elite", word2: "Cable Girls" },
      { word1: "1899", word2: "Dark" },
      { word1: "Wednesday", word2: "You" },
      { word1: "Outer Banks", word2: "Ginny and Georgia" },
    ],
  },
  // ─────────────────────────────────────────────
  // INDIAN WEB SERIES
  // ─────────────────────────────────────────────
  {
    id: "indian-shows",
    name: "Indian Web Series",
    emoji: "🎥",
    description: "Best of OTT India",
    games: ["wordspy", "dumbcharades"],
    pairs: [
      { word1: "Mirzapur", word2: "Panchayat" },
      { word1: "Scam 1992", word2: "Scam 2003" },
      { word1: "Sacred Games", word2: "Delhi Crime" },
      { word1: "Aspirants", word2: "Kota Factory" },
      { word1: "TVF Pitchers", word2: "Shark Tank India" },
      { word1: "Farzi", word2: "Guns and Gulaabs" },
      { word1: "The Family Man", word2: "Special Ops" },
      { word1: "Breathe", word2: "Hostages" },
      { word1: "Jamtara", word2: "Aranyak" },
      { word1: "Four More Shots Please", word2: "Made in Heaven" },
      { word1: "Bandish Bandits", word2: "Gullak" },
      { word1: "Rocket Boys", word2: "Maharani" },
      { word1: "Aarya", word2: "Abhay" },
      { word1: "Raktanchal", word2: "Bhaukaal" },
      { word1: "Tabbar", word2: "Escaype Live" },
      { word1: "Immature", word2: "Hostel Daze" },
      { word1: "Flames", word2: "Little Things" },
      { word1: "Permanent Roommates", word2: "Tripling" },
      { word1: "Humorously Yours", word2: "Dice Media" },
      { word1: "College Romance", word2: "Engineering Girls" },
    ],
  },
];