const games = [
  {
    name: "Wordspy",
    emoji: "🕵️",
    description: "Find the undercover before they escape.",
    href: process.env.NEXT_PUBLIC_WORDSPY_URL,
    accent: "#CC785C",
    bg: "#FFF8F5",
    players: "4–10",
  },
  {
    name: "Mafia",
    emoji: "🔪",
    description: "Lies, alliances, betrayal. Vote wisely.",
    href: process.env.NEXT_PUBLIC_MAFIA_URL,
    accent: "#374151",
    bg: "#F9FAFB",
    players: "5–15",
  },
  {
    name: "Dumb Charades",
    emoji: "🎬",
    description: "Act it out, no talking. Guess before time runs out.",
    href: process.env.NEXT_PUBLIC_DUMBCHARADES_URL,
    accent: "#E85D2F",
    bg: "#FFF3EF",
    players: "4+",
  },
  {
    name: "Pictionary",
    emoji: "🎨",
    description: "Draw it, guess it. No letters, just art.",
    href: process.env.NEXT_PUBLIC_PICITIONARY_URL,
    accent: "#4A6CF7",
    bg: "#EEF2FF",
    players: "4+",
  },
];