/**
 * src/db/generateSeed.ts
 *
 * Generates seed.sql from the shared WORD_PACKS constant in @playhub/core.
 *
 * Usage (from the repo root):
 *   npx ts-node --project src/tsconfig.json src/db/generateSeed.ts > src/db/seed.sql
 *
 * Or with tsx:
 *   npx tsx src/db/generateSeed.ts > src/db/seed.sql
 */

import { WORD_PACKS, type GameId } from "../../packages/core/src/wordPacks";

// Map pack.games array → which game rows to create
// The schema has one word_pack row per (pack, game) combination.
// Words are inserted per pack row so Supabase queries like
//   .eq('game', 'wordspy') correctly return the right packs + words.

function escape(s: string): string {
  return s.replace(/'/g, "''");
}

function categoryFor(packId: string): string {
  if (packId.includes("bollywood") || packId.includes("tollywood")) return "movies";
  if (packId.includes("cricket") || packId.includes("sport")) return "sports";
  if (packId.includes("actor")) return "actors";
  if (packId.includes("music") || packId.includes("song")) return "music";
  if (packId.includes("politics")) return "politics";
  if (packId.includes("food")) return "food";
  if (packId.includes("animal")) return "animals";
  if (packId.includes("profession")) return "professions";
  if (packId.includes("show") || packId.includes("series")) return "tv";
  if (packId.includes("wavelength")) return "spectrum";
  return "general";
}

const lines: string[] = [
  "-- ============================================================",
  "-- PlayHub — Seed Data (auto-generated by generateSeed.ts)",
  "-- Run AFTER schema.sql and rls.sql in the Supabase SQL editor",
  "-- ============================================================",
  "",
  "-- Wrap everything in a transaction so it's all-or-nothing",
  "begin;",
  "",
  "-- Clear existing seed data (idempotent re-run)",
  "truncate words, word_packs restart identity cascade;",
  "",
];

for (const pack of WORD_PACKS) {
  const games: GameId[] = pack.games as GameId[];

  for (const game of games) {
    const packVar = `pack_${pack.id.replace(/-/g, "_")}_${game}`;
    const category = categoryFor(pack.id);

    lines.push(`-- ── ${pack.name} (${game}) ─────────────────────────────────────`);
    lines.push(`do $$ declare ${packVar} uuid;`);
    lines.push(`begin`);
    lines.push(
      `  insert into word_packs (game, name, category, emoji, description, is_active)`
    );
    lines.push(
      `  values ('${game}', '${escape(pack.name)}', '${category}', '${escape(pack.emoji ?? "")}', '${escape(pack.description ?? "")}', true)`
    );
    lines.push(`  returning id into ${packVar};`);
    lines.push(``);
    lines.push(`  insert into words (pack_id, word_a, word_b, difficulty) values`);

    const wordLines = pack.pairs.map(
      (p, i) =>
        `    (${packVar}, '${escape(p.word1)}', '${escape(p.word2)}', 2)` +
        (i < pack.pairs.length - 1 ? "," : ";")
    );
    lines.push(...wordLines);

    lines.push(`end $$;`);
    lines.push(``);
  }
}

lines.push("commit;");
lines.push("");
lines.push("-- Verify");
lines.push("select game, count(*) as packs from word_packs group by game order by game;");

console.log(lines.join("\n"));
