export interface WordPair {
  civilian: string;
  undercover: string;
}

export interface WordPack {
  id: string;
  name: string;
  emoji: string;
  description: string;
  pairs: WordPair[];
}

export const WORD_PACKS: WordPack[] = [
  {
    id: "bollywood",
    name: "Bollywood",
    emoji: "🎬",
    description: "Hindi cinema 2000–2025",
    pairs: [
      { civilian: "Lagaan", undercover: "Swades" },
      { civilian: "Dilwale", undercover: "Mohabbatein" },
      { civilian: "Kabhi Khushi Kabhie Gham", undercover: "Kabhi Alvida Naa Kehna" },
      { civilian: "Devdas", undercover: "Devdas (2002)" },
      { civilian: "Dhoom", undercover: "Dhoom 2" },
      { civilian: "Rang De Basanti", undercover: "Lakshya" },
      { civilian: "Munna Bhai MBBS", undercover: "Lage Raho Munna Bhai" },
      { civilian: "3 Idiots", undercover: "PK" },
      { civilian: "Taare Zameen Par", undercover: "Stanley Ka Dabba" },
      { civilian: "Jab We Met", undercover: "Love Aaj Kal" },
      { civilian: "Chak De India", undercover: "Bhaag Milkha Bhaag" },
      { civilian: "Dabangg", undercover: "Singham" },
      { civilian: "Zindagi Na Milegi Dobara", undercover: "Dil Dhadakne Do" },
      { civilian: "Barfi", undercover: "Rockstar" },
      { civilian: "Gangs of Wasseypur", undercover: "Ugly" },
      { civilian: "Queen", undercover: "Highway" },
      { civilian: "Bajrangi Bhaijaan", undercover: "Sultan" },
      { civilian: "Dangal", undercover: "Secret Superstar" },
      { civilian: "Raazi", undercover: "Uri" },
      { civilian: "Gully Boy", undercover: "Divine" },
      { civilian: "Andhadhun", undercover: "Badla" },
      { civilian: "Article 15", undercover: "Thappad" },
      { civilian: "Shershaah", undercover: "Sam Bahadur" },
      { civilian: "Pathaan", undercover: "War" },
      { civilian: "Brahmastra", undercover: "Kalki 2898 AD" },
      { civilian: "Animal", undercover: "Kabir Singh" },
      { civilian: "Rocky Aur Rani", undercover: "Ae Dil Hai Mushkil" },
      { civilian: "Jawan", undercover: "Chennai Express" },
      { civilian: "Laal Singh Chaddha", undercover: "PK" },
      { civilian: "12th Fail", undercover: "Super 30" },
    ],
  },
  {
    id: "tollywood",
    name: "Tollywood",
    emoji: "🎭",
    description: "Telugu & Tamil cinema 2000–2025",
    pairs: [
      { civilian: "Baahubali", undercover: "RRR" },
      { civilian: "Pushpa", undercover: "Arjun Reddy" },
      { civilian: "Magadheera", undercover: "Eega" },
      { civilian: "Pokiri", undercover: "Athadu" },
      { civilian: "Sye Raa", undercover: "Khaidi No 150" },
      { civilian: "Jersey", undercover: "Maharshi" },
      { civilian: "Ala Vaikunthapurramuloo", undercover: "Sarrainodu" },
      { civilian: "Bimbisara", undercover: "Naragasura" },
      { civilian: "Vikram", undercover: "Kaithi" },
      { civilian: "Master", undercover: "Beast" },
      { civilian: "96", undercover: "Pariyerum Perumal" },
      { civilian: "Mersal", undercover: "Bigil" },
      { civilian: "Kabali", undercover: "Kaala" },
      { civilian: "Enthiran", undercover: "2.0" },
      { civilian: "Vinnaithaandi Varuvaayaa", undercover: "OK Kanmani" },
      { civilian: "Soorarai Pottru", undercover: "Jai Bhim" },
      { civilian: "Vikram Vedha", undercover: "Karthikeya 2" },
      { civilian: "HanuMan", undercover: "Kalki 2898 AD" },
      { civilian: "Salaar", undercover: "KGF" },
      { civilian: "Devara", undercover: "Leo" },
    ],
  },
  {
    id: "south-food",
    name: "South Indian Food",
    emoji: "🍛",
    description: "Classic dishes from South India",
    pairs: [
      { civilian: "Dosa", undercover: "Uttapam" },
      { civilian: "Idli", undercover: "Vada" },
      { civilian: "Sambar", undercover: "Rasam" },
      { civilian: "Biryani", undercover: "Pulao" },
      { civilian: "Pongal", undercover: "Khichdi" },
      { civilian: "Appam", undercover: "Dosa" },
      { civilian: "Chettinad Curry", undercover: "Madras Curry" },
      { civilian: "Pesarattu", undercover: "Dosa" },
      { civilian: "Puttu", undercover: "Idiyappam" },
      { civilian: "Payasam", undercover: "Kheer" },
      { civilian: "Coconut Chutney", undercover: "Mint Chutney" },
      { civilian: "Filter Coffee", undercover: "Chai" },
      { civilian: "Murukku", undercover: "Chakli" },
      { civilian: "Hyderabadi Biryani", undercover: "Lucknowi Biryani" },
      { civilian: "Bisi Bele Bath", undercover: "Pongal" },
      { civilian: "Medu Vada", undercover: "Dal Vada" },
      { civilian: "Avial", undercover: "Mixed Veg Curry" },
      { civilian: "Curd Rice", undercover: "Rajma Rice" },
      { civilian: "Banana Leaf Meal", undercover: "Thali" },
      { civilian: "Tamarind Rice", undercover: "Lemon Rice" },
    ],
  },
  {
    id: "north-food",
    name: "North Indian Food",
    emoji: "🫓",
    description: "Flavours from the North",
    pairs: [
      { civilian: "Butter Chicken", undercover: "Dal Makhani" },
      { civilian: "Naan", undercover: "Roti" },
      { civilian: "Rajma Chawal", undercover: "Dal Chawal" },
      { civilian: "Chole Bhature", undercover: "Puri Sabzi" },
      { civilian: "Paneer Tikka", undercover: "Chicken Tikka" },
      { civilian: "Lassi", undercover: "Chaas" },
      { civilian: "Kulfi", undercover: "Ice Cream" },
      { civilian: "Gajar Ka Halwa", undercover: "Moong Dal Halwa" },
      { civilian: "Samosa", undercover: "Kachori" },
      { civilian: "Gulab Jamun", undercover: "Rasgulla" },
      { civilian: "Paratha", undercover: "Thepla" },
      { civilian: "Aloo Tikki", undercover: "Aloo Chaat" },
      { civilian: "Palak Paneer", undercover: "Saag Gosht" },
      { civilian: "Biryani", undercover: "Pulao" },
      { civilian: "Jalebi", undercover: "Imarti" },
    ],
  },
  {
    id: "street-food",
    name: "Desi Street Food",
    emoji: "🥘",
    description: "India's best street eats",
    pairs: [
      { civilian: "Pani Puri", undercover: "Sev Puri" },
      { civilian: "Vada Pav", undercover: "Dabeli" },
      { civilian: "Pav Bhaji", undercover: "Misal Pav" },
      { civilian: "Bhel Puri", undercover: "Bhel" },
      { civilian: "Kathi Roll", undercover: "Frankie" },
      { civilian: "Chaat", undercover: "Papdi Chaat" },
      { civilian: "Litti Chokha", undercover: "Bati Churma" },
      { civilian: "Egg Roll", undercover: "Kathi Roll" },
      { civilian: "Momos", undercover: "Dimsums" },
      { civilian: "Dahi Papdi", undercover: "Dahi Vada" },
      { civilian: "Aloo Chaat", undercover: "Tikki Chaat" },
      { civilian: "Corn Bhel", undercover: "Bhel Puri" },
      { civilian: "Falooda", undercover: "Rose Milk" },
      { civilian: "Kulhad Chai", undercover: "Tapri Chai" },
    ],
  },
  {
    id: "cricket",
    name: "Cricket",
    emoji: "🏏",
    description: "India's religion",
    pairs: [
      { civilian: "Virat Kohli", undercover: "Rohit Sharma" },
      { civilian: "MS Dhoni", undercover: "Sourav Ganguly" },
      { civilian: "IPL", undercover: "T20 World Cup" },
      { civilian: "Test Match", undercover: "ODI" },
      { civilian: "Mumbai Indians", undercover: "Chennai Super Kings" },
      { civilian: "Eden Gardens", undercover: "Wankhede" },
      { civilian: "Yorker", undercover: "Bouncer" },
      { civilian: "Six", undercover: "Four" },
      { civilian: "LBW", undercover: "Caught Behind" },
      { civilian: "Sachin Tendulkar", undercover: "Brian Lara" },
      { civilian: "Jasprit Bumrah", undercover: "Mohammed Shami" },
      { civilian: "Spin Bowling", undercover: "Pace Bowling" },
      { civilian: "Cover Drive", undercover: "Pull Shot" },
      { civilian: "DRS", undercover: "Third Umpire" },
      { civilian: "Powerplay", undercover: "Death Overs" },
    ],
  },
  {
    id: "cities",
    name: "Indian Cities",
    emoji: "🏙️",
    description: "From metros to hidden gems",
    pairs: [
      { civilian: "Mumbai", undercover: "Pune" },
      { civilian: "Hyderabad", undercover: "Secunderabad" },
      { civilian: "Chennai", undercover: "Coimbatore" },
      { civilian: "Delhi", undercover: "Noida" },
      { civilian: "Bengaluru", undercover: "Mysuru" },
      { civilian: "Kolkata", undercover: "Howrah" },
      { civilian: "Jaipur", undercover: "Udaipur" },
      { civilian: "Ahmedabad", undercover: "Surat" },
      { civilian: "Goa", undercover: "Pondicherry" },
      { civilian: "Varanasi", undercover: "Prayagraj" },
      { civilian: "Amritsar", undercover: "Ludhiana" },
      { civilian: "Kochi", undercover: "Thiruvananthapuram" },
      { civilian: "Visakhapatnam", undercover: "Vijayawada" },
      { civilian: "Shimla", undercover: "Manali" },
    ],
  },
  {
    id: "festivals",
    name: "Indian Festivals",
    emoji: "🪔",
    description: "Celebrations across India",
    pairs: [
      { civilian: "Diwali", undercover: "Dussehra" },
      { civilian: "Holi", undercover: "Basant Panchami" },
      { civilian: "Eid ul-Fitr", undercover: "Eid ul-Adha" },
      { civilian: "Pongal", undercover: "Makar Sankranti" },
      { civilian: "Onam", undercover: "Vishu" },
      { civilian: "Navratri", undercover: "Garba" },
      { civilian: "Ganesh Chaturthi", undercover: "Durga Puja" },
      { civilian: "Baisakhi", undercover: "Lohri" },
      { civilian: "Ugadi", undercover: "Gudi Padwa" },
      { civilian: "Bihu", undercover: "Rongali Bihu" },
      { civilian: "Christmas", undercover: "New Year" },
      { civilian: "Janmashtami", undercover: "Ram Navami" },
    ],
  },
  {
    id: "web-series",
    name: "Indian Web Series",
    emoji: "📺",
    description: "OTT hits from India",
    pairs: [
      { civilian: "Mirzapur", undercover: "Panchayat" },
      { civilian: "Scam 1992", undercover: "Rocket Boys" },
      { civilian: "Sacred Games", undercover: "Delhi Crime" },
      { civilian: "Aspirants", undercover: "Kota Factory" },
      { civilian: "TVF Pitchers", undercover: "Shark Tank India" },
      { civilian: "Bandish Bandits", undercover: "Tabbar" },
      { civilian: "The Family Man", undercover: "Special Ops" },
      { civilian: "Four More Shots Please", undercover: "Girl in the City" },
      { civilian: "Breathe", undercover: "Hostages" },
      { civilian: "Made in Heaven", undercover: "Broken But Beautiful" },
      { civilian: "Jamtara", undercover: "Aranyak" },
      { civilian: "Aarya", undercover: "Bhaukaal" },
    ],
  },
  {
    id: "actors",
    name: "Bollywood Actors",
    emoji: "🌟",
    description: "Stars of Hindi cinema",
    pairs: [
      { civilian: "Shah Rukh Khan", undercover: "Salman Khan" },
      { civilian: "Deepika Padukone", undercover: "Priyanka Chopra" },
      { civilian: "Ranveer Singh", undercover: "Ranbir Kapoor" },
      { civilian: "Alia Bhatt", undercover: "Katrina Kaif" },
      { civilian: "Amitabh Bachchan", undercover: "Dharmendra" },
      { civilian: "Ayushmann Khurrana", undercover: "Rajkummar Rao" },
      { civilian: "Taapsee Pannu", undercover: "Bhumi Pednekar" },
      { civilian: "Prabhas", undercover: "Allu Arjun" },
      { civilian: "Vijay Deverakonda", undercover: "Kartik Aaryan" },
      { civilian: "Kangana Ranaut", undercover: "Vidya Balan" },
      { civilian: "Nawazuddin Siddiqui", undercover: "Manoj Bajpayee" },
      { civilian: "Hrithik Roshan", undercover: "Tiger Shroff" },
    ],
  },
];

export function getRandomPair(packId: string): WordPair {
  const pack = WORD_PACKS.find((p) => p.id === packId);
  if (!pack) return { civilian: "Dosa", undercover: "Uttapam" };
  return pack.pairs[Math.floor(Math.random() * pack.pairs.length)];
}

export function getPackById(packId: string): WordPack | undefined {
  return WORD_PACKS.find((p) => p.id === packId);
}
