export interface WordPair {
  civilian: string;
  undercover: string;
}

export interface WordPack {
  id: string;
  name: string;
  emoji: string;
  description: string;
  pairs: WordPair[];
}

export const WORD_PACKS: WordPack[] = [
  {
    id: "bollywood",
    name: "Bollywood",
    emoji: "🎬",
    description: "Hindi cinema 2000–2025",
    pairs: [
      { civilian: "Lagaan", undercover: "Swades" },
      { civilian: "Dilwale", undercover: "Mohabbatein" },
      { civilian: "Kabhi Khushi Kabhie Gham", undercover: "Kabhi Alvida Naa Kehna" },
      { civilian: "Devdas", undercover: "Umrao Jaan" },
      { civilian: "Dhoom", undercover: "Dhoom 2" },
      { civilian: "Rang De Basanti", undercover: "Lakshya" },
      { civilian: "Munna Bhai MBBS", undercover: "Lage Raho Munna Bhai" },
      { civilian: "3 Idiots", undercover: "Chhichhore" },
      { civilian: "Taare Zameen Par", undercover: "Stanley Ka Dabba" },
      { civilian: "Jab We Met", undercover: "Love Aaj Kal" },
      { civilian: "Chak De India", undercover: "Bhaag Milkha Bhaag" },
      { civilian: "Dabangg", undercover: "Singham" },
      { civilian: "Zindagi Na Milegi Dobara", undercover: "Dil Dhadakne Do" },
      { civilian: "Barfi", undercover: "Rockstar" },
      { civilian: "Gangs of Wasseypur", undercover: "Ugly" },
      { civilian: "Queen", undercover: "Highway" },
      { civilian: "Bajrangi Bhaijaan", undercover: "Sultan" },
      { civilian: "Dangal", undercover: "Secret Superstar" },
      { civilian: "Raazi", undercover: "Uri" },
      { civilian: "Gully Boy", undercover: "Udta Punjab" },
      { civilian: "Andhadhun", undercover: "Badla" },
      { civilian: "Article 15", undercover: "Thappad" },
      { civilian: "Shershaah", undercover: "Sam Bahadur" },
      { civilian: "Pathaan", undercover: "War" },
      { civilian: "Brahmastra", undercover: "Kalki 2898 AD" },
      { civilian: "Animal", undercover: "Kabir Singh" },
      { civilian: "Rocky Aur Rani", undercover: "Ae Dil Hai Mushkil" },
      { civilian: "Jawan", undercover: "Bade Miyan Chote Miyan" },
      { civilian: "Laal Singh Chaddha", undercover: "Atrangi Re" },
      { civilian: "12th Fail", undercover: "Super 30" },
      { civilian: "Ghar Ek Mandir", undercover: "Tanhaji" },
      { civilian: "Kal Ho Naa Ho", undercover: "Dil To Pagal Hai" },
      { civilian: "Hera Pheri", undercover: "Welcome" },
      { civilian: "Golmaal", undercover: "Bhool Bhulaiya" },
      { civilian: "Munnabhai MBBS", undercover: "Khosla Ka Ghosla" },
    ],
  },
  {
    id: "tollywood",
    name: "Tollywood",
    emoji: "🎭",
    description: "Telugu & Tamil cinema 2000–2025",
    pairs: [
      { civilian: "Baahubali", undercover: "RRR" },
      { civilian: "Pushpa", undercover: "Arjun Reddy" },
      { civilian: "Magadheera", undercover: "Eega" },
      { civilian: "Pokiri", undercover: "Athadu" },
      { civilian: "Sye Raa", undercover: "Khaidi No 150" },
      { civilian: "Jersey", undercover: "Maharshi" },
      { civilian: "Ala Vaikunthapurramuloo", undercover: "Sarrainodu" },
      { civilian: "Bimbisara", undercover: "Chandramukhi" },
      { civilian: "Vikram", undercover: "Kaithi" },
      { civilian: "Master", undercover: "Beast" },
      { civilian: "96", undercover: "Pariyerum Perumal" },
      { civilian: "Mersal", undercover: "Bigil" },
      { civilian: "Kabali", undercover: "Kaala" },
      { civilian: "Enthiran", undercover: "2.0" },
      { civilian: "Vinnaithaandi Varuvaayaa", undercover: "OK Kanmani" },
      { civilian: "Soorarai Pottru", undercover: "Jai Bhim" },
      { civilian: "Vikram Vedha", undercover: "Karthikeya 2" },
      { civilian: "HanuMan", undercover: "Ayodhya" },
      { civilian: "Salaar", undercover: "KGF" },
      { civilian: "Devara", undercover: "Leo" },
      { civilian: "Jyotiba Phule", undercover: "Padmaavat" },
      { civilian: "Aranmanai", undercover: "Stree" },
      { civilian: "Oh My Kadavule", undercover: "96" },
      { civilian: "Jai Lava Kusa", undercover: "Temper" },
      { civilian: "I", undercover: "Kabali" },
      { civilian: "Janatha Garage", undercover: "Natarang" },
    ],
  },
  {
    id: "south-food",
    name: "South Indian Food",
    emoji: "🍛",
    description: "Classic dishes from South India",
    pairs: [
      { civilian: "Dosa", undercover: "Uttapam" },
      { civilian: "Idli", undercover: "Vada" },
      { civilian: "Sambar", undercover: "Rasam" },
      { civilian: "Biryani", undercover: "Pulao" },
      { civilian: "Pongal", undercover: "Khichdi" },
      { civilian: "Appam", undercover: "Idiyappam" },
      { civilian: "Chettinad Curry", undercover: "Madras Curry" },
      { civilian: "Pesarattu", undercover: "Paniyaram" },
      { civilian: "Puttu", undercover: "String Hoppers" },
      { civilian: "Payasam", undercover: "Kheer" },
      { civilian: "Coconut Chutney", undercover: "Groundnut Chutney" },
      { civilian: "Filter Coffee", undercover: "Chai" },
      { civilian: "Murukku", undercover: "Chakli" },
      { civilian: "Hyderabadi Biryani", undercover: "Lucknowi Biryani" },
      { civilian: "Bisi Bele Bath", undercover: "Lemon Rice" },
      { civilian: "Medu Vada", undercover: "Bonda" },
      { civilian: "Avial", undercover: "Stir-Fried Vegetables" },
      { civilian: "Curd Rice", undercover: "Yogurt Rice" },
      { civilian: "Banana Leaf Meal", undercover: "Thali" },
      { civilian: "Tamarind Rice", undercover: "Mango Rice" },
      { civilian: "Tiffin Sambar", undercover: "Sambhar Powder" },
      { civilian: "Gunpowder Chutney", undercover: "Tomato Chutney" },
      { civilian: "Jaggery Payasam", undercover: "Semolina Halwa" },
      { civilian: "Dhal Puri", undercover: "Chikhalwali" },
      { civilian: "Spinach Vada", undercover: "Chilli Pakoda" },
      { civilian: "Sesame Laddu", undercover: "Peanut Brittle" },
    ],
  },
  {
    id: "north-food",
    name: "North Indian Food",
    emoji: "🫓",
    description: "Flavours from the North",
    pairs: [
      { civilian: "Butter Chicken", undercover: "Tandoori Chicken" },
      { civilian: "Naan", undercover: "Roti" },
      { civilian: "Rajma Chawal", undercover: "Dal Chawal" },
      { civilian: "Chole Bhature", undercover: "Puri Sabzi" },
      { civilian: "Paneer Tikka", undercover: "Chicken Tikka" },
      { civilian: "Lassi", undercover: "Chaas" },
      { civilian: "Kulfi", undercover: "Falooda" },
      { civilian: "Gajar Ka Halwa", undercover: "Moong Dal Halwa" },
      { civilian: "Samosa", undercover: "Kachori" },
      { civilian: "Gulab Jamun", undercover: "Rasgulla" },
      { civilian: "Paratha", undercover: "Rumali Roti" },
      { civilian: "Aloo Tikki", undercover: "Batata Vada" },
      { civilian: "Palak Paneer", undercover: "Saag Gosht" },
      { civilian: "Korma", undercover: "Nihari" },
      { civilian: "Jalebi", undercover: "Imarti" },
      { civilian: "Dal Makhani", undercover: "Chole Curry" },
      { civilian: "Kebab", undercover: "Seekh Kabab" },
      { civilian: "Saag Aloo", undercover: "Baingan Bharta" },
      { civilian: "Pav Bhaji", undercover: "Bhelpuri" },
      { civilian: "Matar Paneer", undercover: "Paneer Makhani" },
      { civilian: "Khichdi", undercover: "Pulao" },
      { civilian: "Barfi", undercover: "Peda" },
      { civilian: "Rasgulla", undercover: "Sandesh" },
      { civilian: "Bread Pakora", undercover: "Pakora" },
      { civilian: "Chikhalwali", undercover: "Gujhia" },
    ],
  },
  {
    id: "street-food",
    name: "Desi Street Food",
    emoji: "🥘",
    description: "India's best street eats",
    pairs: [
      { civilian: "Pani Puri", undercover: "Sev Puri" },
      { civilian: "Vada Pav", undercover: "Dabeli" },
      { civilian: "Pav Bhaji", undercover: "Misal Pav" },
      { civilian: "Bhel Puri", undercover: "Aloo Chaat" },
      { civilian: "Kathi Roll", undercover: "Frankie" },
      { civilian: "Chaat", undercover: "Papdi Chaat" },
      { civilian: "Litti Chokha", undercover: "Bati Churma" },
      { civilian: "Egg Roll", undercover: "Paneer Roll" },
      { civilian: "Momos", undercover: "Dimsums" },
      { civilian: "Dahi Papdi", undercover: "Dahi Bhalle" },
      { civilian: "Tikki Chaat", undercover: "Rajma Chaat" },
      { civilian: "Corn Chaat", undercover: "Masala Corn" },
      { civilian: "Falooda", undercover: "Rose Milk" },
      { civilian: "Kulhad Chai", undercover: "Tapri Chai" },
      { civilian: "Gol Gappa", undercover: "Batata Puri" },
      { civilian: "Ragda Pattice", undercover: "Chikhalwali Chaat" },
      { civilian: "Jhal Muri", undercover: "Puffed Rice" },
      { civilian: "Spring Roll", undercover: "Vegetable Roll" },
      { civilian: "Pyaaz Pakora", undercover: "Mirch Pakora" },
      { civilian: "Corn Pakora", undercover: "Spinach Pakora" },
    ],
  },
  {
    id: "cricket",
    name: "Cricket",
    emoji: "🏏",
    description: "India's religion",
    pairs: [
      { civilian: "Virat Kohli", undercover: "Rohit Sharma" },
      { civilian: "MS Dhoni", undercover: "Sourav Ganguly" },
      { civilian: "IPL", undercover: "T20 World Cup" },
      { civilian: "Test Match", undercover: "ODI" },
      { civilian: "Mumbai Indians", undercover: "Chennai Super Kings" },
      { civilian: "Eden Gardens", undercover: "Wankhede" },
      { civilian: "Yorker", undercover: "Bouncer" },
      { civilian: "Six", undercover: "Four" },
      { civilian: "LBW", undercover: "Bowled" },
      { civilian: "Sachin Tendulkar", undercover: "Steve Smith" },
      { civilian: "Jasprit Bumrah", undercover: "Mohammed Shami" },
      { civilian: "Spin Bowling", undercover: "Fast Bowling" },
      { civilian: "Cover Drive", undercover: "Square Cut" },
      { civilian: "DRS", undercover: "Hawkeye" },
      { civilian: "Powerplay", undercover: "Death Overs" },
      { civilian: "Suresh Raina", undercover: "Yuvraj Singh" },
      { civilian: "Anil Kumble", undercover: "Ravichandran Ashwin" },
      { civilian: "Ravindra Jadeja", undercover: "Kuldeep Yadav" },
      { civilian: "Shikhar Dhawan", undercover: "KL Rahul" },
      { civilian: "Hardik Pandya", undercover: "Bumrah" },
      { civilian: "Stumped", undercover: "Caught Out" },
      { civilian: "Maiden Over", undercover: "Dot Ball" },
      { civilian: "Slip Fielding", undercover: "Gully Fielding" },
      { civilian: "Swing Bowling", undercover: "Seam Bowling" },
      { civilian: "Cricket World Cup", undercover: "Asia Cup" },
    ],
  },
  {
    id: "cities",
    name: "Indian Cities",
    emoji: "🏙️",
    description: "From metros to hidden gems",
    pairs: [
      { civilian: "Mumbai", undercover: "Bangalore" },
      { civilian: "Hyderabad", undercover: "Secunderabad" },
      { civilian: "Chennai", undercover: "Coimbatore" },
      { civilian: "Delhi", undercover: "Gurugram" },
      { civilian: "Bengaluru", undercover: "Mysuru" },
      { civilian: "Kolkata", undercover: "Howrah" },
      { civilian: "Jaipur", undercover: "Udaipur" },
      { civilian: "Ahmedabad", undercover: "Surat" },
      { civilian: "Goa", undercover: "Pondicherry" },
      { civilian: "Varanasi", undercover: "Prayagraj" },
      { civilian: "Amritsar", undercover: "Ludhiana" },
      { civilian: "Kochi", undercover: "Thiruvananthapuram" },
      { civilian: "Visakhapatnam", undercover: "Vijayawada" },
      { civilian: "Shimla", undercover: "Nainital" },
      { civilian: "Lucknow", undercover: "Kanpur" },
      { civilian: "Indore", undercover: "Nagpur" },
      { civilian: "Chandigarh", undercover: "Mohali" },
      { civilian: "Pune", undercover: "Nashik" },
      { civilian: "Srinagar", undercover: "Leh" },
      { civilian: "Allahabad", undercover: "Meerut" },
      { civilian: "Bhopal", undercover: "Gwalior" },
      { civilian: "Jamshedpur", undercover: "Raipur" },
      { civilian: "Ranchi", undercover: "Patna" },
      { civilian: "Bhubaneswar", undercover: "Cuttack" },
      { civilian: "Dehradun", undercover: "Haridwar" },
    ],
  },
  {
    id: "festivals",
    name: "Indian Festivals",
    emoji: "🪔",
    description: "Celebrations across India",
    pairs: [
      { civilian: "Diwali", undercover: "Dussehra" },
      { civilian: "Holi", undercover: "Basant Panchami" },
      { civilian: "Eid ul-Fitr", undercover: "Eid ul-Adha" },
      { civilian: "Pongal", undercover: "Makar Sankranti" },
      { civilian: "Onam", undercover: "Vishu" },
      { civilian: "Navratri", undercover: "Garba" },
      { civilian: "Ganesh Chaturthi", undercover: "Durga Puja" },
      { civilian: "Baisakhi", undercover: "Lohri" },
      { civilian: "Ugadi", undercover: "Gudi Padwa" },
      { civilian: "Bihu", undercover: "Assam Day" },
      { civilian: "Christmas", undercover: "Easter" },
      { civilian: "Janmashtami", undercover: "Ram Navami" },
      { civilian: "Raksha Bandhan", undercover: "Bhaya Dooj" },
      { civilian: "Mahavir Jayanti", undercover: "Buddha Purnima" },
      { civilian: "Rakshabandhan", undercover: "Teej" },
      { civilian: "Karva Chauth", undercover: "Maha Shivaratri" },
      { civilian: "Chhath Puja", undercover: "Kumbh Mela" },
      { civilian: "Diwali Lights", undercover: "Diwali Fireworks" },
      { civilian: "Holi Colors", undercover: "Holi Bonfire" },
      { civilian: "New Year", undercover: "New Year's Eve" },
    ],
  },
  {
    id: "web-series",
    name: "Indian Web Series",
    emoji: "📺",
    description: "OTT hits from India",
    pairs: [
      { civilian: "Mirzapur", undercover: "Panchayat" },
      { civilian: "Scam 1992", undercover: "Rocket Boys" },
      { civilian: "Sacred Games", undercover: "Delhi Crime" },
      { civilian: "Aspirants", undercover: "Kota Factory" },
      { civilian: "TVF Pitchers", undercover: "Shark Tank India" },
      { civilian: "Bandish Bandits", undercover: "Tabbar" },
      { civilian: "The Family Man", undercover: "Special Ops" },
      { civilian: "Four More Shots Please", undercover: "Girl in the City" },
      { civilian: "Breathe", undercover: "Hostages" },
      { civilian: "Made in Heaven", undercover: "Broken But Beautiful" },
      { civilian: "Jamtara", undercover: "Aranyak" },
      { civilian: "Aarya", undercover: "Bhaukaal" },
      { civilian: "Gullak", undercover: "Kahaniyaan" },
      { civilian: "Panchayat 2", undercover: "Mirzapur 3" },
      { civilian: "Andhadhun Series", undercover: "Badla" },
      { civilian: "Criminal Justice", undercover: "Section 375" },
      { civilian: "Yeh Kaali Kaali Ankhein", undercover: "She" },
      { civilian: "Masaba Masaba", undercover: "The Trial" },
      { civilian: "Unpaused", undercover: "Laxmii" },
      { civilian: "Madhuri Dixit Series", undercover: "Vidya Balan Series" },
      { civilian: "Tandav", undercover: "Tanaav" },
      { civilian: "A Suitable Boy", undercover: "Paatal Lok" },
      { civilian: "Cobalt Blue", undercover: "Srikanto" },
    ],
  },
  {
    id: "actors",
    name: "Bollywood Actors",
    emoji: "🌟",
    description: "Stars of Hindi cinema",
    pairs: [
      { civilian: "Shah Rukh Khan", undercover: "Salman Khan" },
      { civilian: "Deepika Padukone", undercover: "Priyanka Chopra" },
      { civilian: "Ranveer Singh", undercover: "Ranbir Kapoor" },
      { civilian: "Alia Bhatt", undercover: "Katrina Kaif" },
      { civilian: "Amitabh Bachchan", undercover: "Dharmendra" },
      { civilian: "Ayushmann Khurrana", undercover: "Rajkummar Rao" },
      { civilian: "Taapsee Pannu", undercover: "Bhumi Pednekar" },
      { civilian: "Prabhas", undercover: "Allu Arjun" },
      { civilian: "Vijay Deverakonda", undercover: "Kartik Aaryan" },
      { civilian: "Kangana Ranaut", undercover: "Vidya Balan" },
      { civilian: "Nawazuddin Siddiqui", undercover: "Manoj Bajpayee" },
      { civilian: "Hrithik Roshan", undercover: "Tiger Shroff" },
      { civilian: "Akshay Kumar", undercover: "Ajay Devgn" },
      { civilian: "Varun Dhawan", undercover: "Siddhant Chaturvedi" },
      { civilian: "Janhvi Kapoor", undercover: "Sara Ali Khan" },
      { civilian: "Ananya Panday", undercover: "Rakul Preet Singh" },
      { civilian: "Sushant Singh Rajput", undercover: "Sidharth Malhotra" },
      { civilian: "Arjun Kapoor", undercover: "Emraan Hashmi" },
      { civilian: "Akira", undercover: "Madhuri Dixit" },
      { civilian: "Kareena Kapoor", undercover: "Karisma Kapoor" },
      { civilian: "Aishwarya Rai", undercover: "Juhi Chawla" },
      { civilian: "Jacqueline Fernandez", undercover: "Disha Patani" },
      { civilian: "Bobby Deol", undercover: "Sunny Deol" },
      { civilian: "Rishi Kapoor", undercover: "Jeetendra" },
      { civilian: "Sunny Leone", undercover: "Mallika Sherawat" },
      { civilian: "Farhan Akhtar", undercover: "Roshan Abbas" },
    ],
  },
];

export function getRandomPair(packId: string): WordPair {
  const pack = WORD_PACKS.find((p) => p.id === packId);
  if (!pack) return { civilian: "Dosa", undercover: "Uttapam" };
  return pack.pairs[Math.floor(Math.random() * pack.pairs.length)];
}

export function getPackById(packId: string): WordPack | undefined {
  return WORD_PACKS.find((p) => p.id === packId);
}
